function makeId(subject, title) {
  return `${subject}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}`;
}

function subjectName(subject) {
  if (subject === 'language') return 'Language & Thinking';
  return subject === 'cs' ? 'Computer Science' : subject[0].toUpperCase() + subject.slice(1);
}

function buildLearning(subject, stage, title, level, bigIdea, mentalModel, guidedExample, bridge, predictionQuestion, predictionAnswer, quizQuestion, correctAnswer, misconception) {
  const name = subjectName(subject);

  return {
    intuition: {
      plainEnglish: bigIdea,
      concept: mentalModel,
    },
    formalIdea: {
      definition: `${title} is the ${level.toLowerCase()} concept in ${name} for this stage: ${stage}.`,
      terminology: `Key terms: ${title.toLowerCase()}, input, output, relationship, model, assumption, and evidence.`,
    },
    derivation: [
      `Start with the situation: ${bigIdea}`,
      `Name the quantities or parts that matter. In this lesson, the useful mental model is: ${mentalModel}`,
      `Apply the rule carefully rather than guessing. The core working example is: ${guidedExample}`,
      `Check the result against the concept. A good answer should agree with this idea: ${correctAnswer}.`,
    ],
    workedExamples: [
      {
        title: 'Direct application',
        inputs: predictionQuestion,
        steps: [
          'Identify what the problem is asking before calculating.',
          `Use the lesson idea: ${bigIdea}`,
          `Reason through the expected behavior: ${predictionAnswer}`,
        ],
        output: predictionAnswer,
      },
      {
        title: 'Connected application',
        inputs: bridge,
        steps: [
          'Translate the concept into a related subject.',
          'Name the shared structure: inputs, changes, constraints, or outputs.',
          `Use that structure to explain why the connection works: ${bridge}`,
        ],
        output: `The same idea can be used outside this lesson because ${bridge.toLowerCase()}`,
      },
    ],
    practiceProblems: [
      {
        difficulty: 'Easy',
        prompt: `State the main rule of ${title} in one sentence, then give one simple input-output example.`,
        solution: [
          `Main rule: ${bigIdea}`,
          `Example pattern: ${guidedExample}`,
          'The answer is strong if it names the input, the operation or relationship, and the output.',
        ],
      },
      {
        difficulty: 'Medium',
        prompt: quizQuestion,
        solution: [
          `Correct answer: ${correctAnswer}.`,
          `Reason: ${correctAnswer} matches the concept, while "${misconception}" is a common misunderstanding.`,
          'Check the answer by connecting it back to the formal idea, not by memorizing the wording.',
        ],
      },
      {
        difficulty: 'Challenge',
        prompt: `Use ${title} to explain a situation in another field: ${bridge}`,
        solution: [
          'First, identify the shared structure between the lesson and the connected field.',
          `Connection: ${bridge}`,
          'Then explain what changes, what stays constrained, and what evidence would show the idea is working.',
        ],
      },
    ],
    commonMistakes: [
      {
        mistake: misconception,
        whyWrong: `This misses the key relationship. The useful idea is: ${correctAnswer}.`,
      },
      {
        mistake: 'Using the right word but not checking the inputs, assumptions, or units.',
        whyWrong: 'Concepts become reliable only when they are tied to the quantities and conditions in the problem.',
      },
      {
        mistake: 'Treating the example as the only case instead of seeing the general pattern.',
        whyWrong: `The example is evidence for the broader idea: ${bigIdea}`,
      },
    ],
    connections: {
      math: name === 'Math' ? `This is a math idea directly: ${bigIdea}` : 'Math supplies the language for quantities, relationships, rates, and uncertainty.',
      physics: name === 'Physics' ? `This is a physics idea directly: ${bigIdea}` : 'Physics tests the idea against real motion, energy, force, measurement, or signals.',
      computerScience: name === 'Computer Science' ? `This is a computer science idea directly: ${bigIdea}` : 'Computer science turns the idea into procedures, simulations, data structures, or interfaces.',
      ai: 'AI systems use the same habit: define inputs, compare outputs with reality, measure error, and update a model.',
    },
    buildLink: `In labs, test the prediction before changing controls. In Build Mode, write pseudocode that turns "${title}" into inputs, steps, and an output. In real software, this becomes a small model, validator, simulator, or decision rule.`,
  };
}

function lesson(subject, stage, title, level, bigIdea, mentalModel, guidedExample, bridge, predictionQuestion, predictionAnswer, quizQuestion, correctAnswer, misconception) {
  return {
    id: makeId(subject, title),
    subject: subjectName(subject),
    stage,
    title,
    level,
    bigIdea,
    whyItMatters: `${bigIdea} This matters in real projects because ${bridge.toLowerCase()} AI systems also depend on this idea when they measure data, choose actions, or learn from examples.`,
    mentalModel,
    guidedExample,
    bridge,
    prediction: {
      question: predictionQuestion,
      answer: predictionAnswer,
    },
    quiz: {
      question: quizQuestion,
      options: [
        correctAnswer,
        misconception,
        'Memorize the words without checking the relationship',
        'Ignore the inputs and guess from the title',
      ],
      correctIndex: 0,
      feedback: [
        `Correct. ${correctAnswer} is the useful idea to carry forward.`,
        `Not quite. ${misconception} is a common trap, but it misses the structure of this lesson.`,
        'Not quite. Memorizing labels is weaker than reasoning from the relationship.',
        'Not quite. The inputs and constraints are what make the answer meaningful.',
      ],
    },
    learning: buildLearning(subject, stage, title, level, bigIdea, mentalModel, guidedExample, bridge, predictionQuestion, predictionAnswer, quizQuestion, correctAnswer, misconception),
  };
}

const mathStages = {
  arithmetic: 'Arithmetic and number sense',
  algebra: 'Algebra and equations',
  functions: 'Functions and graphing',
  geometry: 'Geometry and trigonometry',
  calculus: 'Calculus foundations',
  probability: 'Probability and statistics',
  linear: 'Linear algebra',
  optimization: 'Optimization and AI math',
};

const physicsStages = {
  measurement: 'Measurement and scientific thinking',
  motion: 'Motion and kinematics',
  forces: 'Forces and Newtonian mechanics',
  energy: 'Energy and momentum',
  waves: 'Waves and oscillations',
  electricity: 'Electricity and circuits',
  systems: 'Systems, constraints, and modeling',
  bridges: 'Physics-to-computation bridges',
};

const csStages = {
  thinking: 'Computational thinking',
  fundamentals: 'Programming fundamentals',
  structures: 'Data structures',
  algorithms: 'Algorithms and Big-O',
  debugging: 'Debugging and testing',
  systems: 'Systems and architecture',
  dataAi: 'Data and AI foundations',
  software: 'Building real software',
};

const languageStages = {
  foundations: 'Foundations',
  intermediate: 'Intermediate',
  advanced: 'Advanced',
};

const mathSpecs = [
  [mathStages.arithmetic, 'Place Value and Scale', 'Foundation', 'Place value tells how much each digit contributes, so 4 in 400 is ten times the 4 in 40.', 'Think of each digit as sitting in a seat with a different power of ten.', 'In 3,482, the 3 means 3 thousands, not just 3.', 'Physics measurements and computer memory sizes both depend on understanding scale.', 'If you multiply 56 by 10, what changes?', 'Each digit shifts one place left, giving 560.', 'What does place value help you understand?', 'The size contribution of each digit', 'Only the order digits were typed'],
  [mathStages.arithmetic, 'Fractions as Ratios', 'Foundation', 'A fraction compares a part to a whole or one quantity to another.', 'A fraction is a zoomed-in description of sharing.', '3/4 means three equal parts out of four, or 0.75 of the whole.', 'Ratios describe speed, density, probability, and data splits in AI training.', 'Which is larger: 1/2 or 1/3?', '1/2 is larger because the whole is split into fewer pieces.', 'What does 5/8 mean?', 'Five equal parts out of eight', 'Five minus eight'],
  [mathStages.arithmetic, 'Decimals and Precision', 'Foundation', 'Decimals extend place value to parts smaller than one.', 'A decimal point is a border between whole units and smaller pieces.', '0.25 means 25 hundredths, which equals 1/4.', 'Physics sensors and AI datasets often store measurements as decimals with limited precision.', 'Is 0.8 bigger than 0.75?', 'Yes. 0.80 is greater than 0.75.', 'Why can 0.50 equal 0.5?', 'Trailing zeros do not change the value', 'More digits always means a larger value'],
  [mathStages.arithmetic, 'Negative Numbers and Direction', 'Foundation', 'Negative numbers represent values below zero or movement in the opposite direction.', 'Zero is a reference point; negatives live on the other side.', 'A temperature change from 3 to -2 is a drop of 5 degrees.', 'Velocity, charge, error, and program offsets all use signed numbers.', 'If your balance is -7 and you add 10, where do you land?', 'You land at 3.', 'What does a negative sign often show?', 'Opposite direction or below a reference point', 'A number that cannot be used'],
  [mathStages.arithmetic, 'Estimation and Reasonableness', 'Foundation', 'Estimation checks whether an answer makes sense before you trust it.', 'Estimation is a reality filter for calculations.', '19 x 51 is close to 20 x 50, so the answer should be near 1000.', 'Scientists estimate before measuring, and programmers estimate performance before scaling a system.', 'Should 49 x 21 be closer to 100 or 1000?', 'It should be closer to 1000.', 'Why estimate?', 'To catch unreasonable answers early', 'To avoid understanding the problem'],
  [mathStages.arithmetic, 'Exponents and Powers', 'Foundation', 'An exponent tells how many times to multiply a base by itself, so 2^3 means 2 x 2 x 2 = 8.', 'An exponent is a repeat-multiplication counter placed above the base.', '3^4 = 3 x 3 x 3 x 3 = 81, and any nonzero number raised to the zero power equals 1.', 'Computer memory sizes use powers of 2, scientific notation uses powers of 10, and squaring appears throughout physics — kinetic energy uses speed squared and the Pythagorean theorem uses side lengths squared.', 'What does 2^5 equal?', '32, because 2 x 2 x 2 x 2 x 2 = 32.', 'What does any nonzero number raised to the zero power equal?', '1, because removing all repeated factors leaves the multiplicative identity', '0, because multiplying by zero removes any value'],
  [mathStages.algebra, 'Variables as Unknowns', 'Foundation', 'A variable names a value that can change or has not been found yet.', 'A variable is a labeled box for a number.', 'If x + 6 = 14, x is the missing value 8.', 'Physics formulas and programs both use variables to represent changing quantities.', 'If y - 5 = 2, what is y?', 'y is 7.', 'What is a variable?', 'A name for a changing or unknown value', 'A symbol with no meaning'],
  [mathStages.algebra, 'Balancing Equations', 'Foundation', 'Solving equations means keeping both sides equal while isolating the unknown.', 'An equation is a balance scale; equal moves keep it level.', 'For 2x = 12, divide both sides by 2 to get x = 6.', 'Balancing equations appears in forces, circuits, and program constraints.', 'What should you do to both sides of x + 9 = 20?', 'Subtract 9 from both sides.', 'Why do the same operation to both sides?', 'To preserve equality', 'To make the equation look longer'],
  [mathStages.algebra, 'Distributive Property', 'Foundation', 'The distributive property connects multiplication across addition.', 'One multiplier can be handed out to every term inside parentheses.', '3(x + 4) becomes 3x + 12.', 'This helps simplify physics formulas and optimize repeated code calculations.', 'What is 2(a + 5)?', '2a + 10.', 'What does distribution do?', 'Multiplies each term inside the group', 'Deletes the parentheses and changes nothing else'],
  [mathStages.algebra, 'Solving Multi-Step Equations', 'Core', 'Multi-step equations require undoing operations in a careful order.', 'Work backward through the operations that were applied to the variable.', 'For 4x - 3 = 17, add 3 to get 4x = 20, then divide by 4 to get x = 5.', 'Robotics, finance, and simulations often require solving for a hidden input.', 'What is the first step in 5x + 2 = 27?', 'Subtract 2 from both sides.', 'How do you solve multi-step equations?', 'Undo operations while keeping both sides balanced', 'Guess once and stop checking'],
  [mathStages.algebra, 'Inequalities and Constraints', 'Core', 'Inequalities describe ranges of possible values instead of one exact value.', 'A constraint is a fence around allowed answers.', 'x < 10 means any value less than 10 works, not just one number.', 'Physics limits, safety rules, and software validation all use constraints.', 'If speed must be at most 30, is 35 allowed?', 'No. 35 breaks the constraint.', 'What does an inequality describe?', 'A set or range of allowed values', 'Only one exact solution every time'],
  [mathStages.functions, 'Inputs and Outputs', 'Foundation', 'A function maps each input to one output by following a rule.', 'A function is a machine with a dependable behavior.', 'f(x) = 2x + 1 gives f(4) = 9.', 'Programs, physics models, and AI networks all act like input-output systems.', 'If f(x)=x+3, what is f(10)?', '13.', 'What defines a function?', 'A rule connecting inputs to outputs', 'A random collection of answers'],
  [mathStages.functions, 'Coordinate Plane', 'Foundation', 'The coordinate plane locates points using horizontal and vertical values.', 'Coordinates are an address system for a flat world.', '(3, -2) means move 3 right and 2 down from the origin.', 'Graphs of motion, game maps, and image pixels all use coordinate ideas.', 'Where is (0, 5)?', 'On the y-axis, 5 units above the origin.', 'What does an ordered pair show?', 'A horizontal and vertical location', 'Only the distance from zero'],
  [mathStages.functions, 'Linear Functions', 'Core', 'A linear function changes by a constant amount each step.', 'A line is a relationship with steady change.', 'y = 3x + 2 increases by 3 whenever x increases by 1.', 'Constant velocity in physics and simple cost models are linear relationships.', 'What is the slope of y = 4x - 1?', '4.', 'What makes a function linear?', 'A constant rate of change', 'A graph that must pass through zero'],
  [mathStages.functions, 'Nonlinear Patterns', 'Core', 'Nonlinear functions change at rates that are not constant.', 'A curve shows that the rule itself changes as inputs grow.', 'y = x^2 grows from 1 to 4 to 9 as x moves 1, 2, 3.', 'Acceleration, area, epidemics, and neural networks often behave nonlinearly.', 'Does x^2 grow by the same amount each step?', 'No. The increases get larger.', 'What is a nonlinear pattern?', 'A relationship with changing rate of change', 'A line with a hidden label'],
  [mathStages.functions, 'Reading Graphs Critically', 'Core', 'Graphs communicate relationships, but scales and labels control what the picture means.', 'A graph is an argument with axes; inspect the axes before believing the shape.', 'A small vertical scale can make tiny changes look dramatic.', 'Data dashboards and AI evaluations can mislead if graphs are read carelessly.', 'What should you check first on a graph?', 'The labels, units, and scale.', 'Why inspect graph axes?', 'They determine how the visual pattern should be interpreted', 'They are decoration only'],
  [mathStages.functions, 'Logarithms', 'Core', 'A logarithm asks what exponent was used: log base 2 of 8 equals 3 because 2^3 = 8.', 'A logarithm is the undo operation for an exponent, the same way subtraction undoes addition.', 'log2(1024) = 10 because 2^10 = 1024, so binary search on 1024 sorted items takes at most 10 comparisons.', 'Binary search runs in O(log n) time making logarithms central to algorithm analysis, the natural log ln appears in derivatives of exponential functions and in continuous growth models, and log base 2 measures bits of information used directly in AI cross-entropy loss functions.', 'If log10(x) = 3, what is x?', '1000, because 10^3 = 1000.', 'What does log2(8) equal?', '3, because 2^3 = 8', '8, because the log equals the number inside the parentheses'],
  [mathStages.geometry, 'Angles and Rotation', 'Foundation', 'Angles measure turning, not just corner shape.', 'An angle is a record of how far something rotated.', 'A right angle is a quarter turn, or 90 degrees.', 'Robots, games, navigation, and wave phase all depend on rotation.', 'How many degrees are in a half turn?', '180 degrees.', 'What does an angle measure?', 'Amount of turn', 'Length of a side only'],
  [mathStages.geometry, 'Triangles and Similarity', 'Core', 'Similar triangles have the same shape, so their side ratios match.', 'Similarity is shape preservation under scaling.', 'A 3-4-5 triangle and a 6-8-10 triangle are similar.', 'Scale models, camera geometry, and physics diagrams use similar triangles.', 'If one triangle is a doubled copy, what happens to its angles?', 'The angles stay the same.', 'What stays equal in similar triangles?', 'Corresponding angles and side ratios', 'All side lengths exactly'],
  [mathStages.geometry, 'Pythagorean Theorem', 'Core', 'In a right triangle, a^2 + b^2 = c^2 connects the legs and hypotenuse.', 'The theorem measures straight-line distance from square steps.', 'A triangle with legs 6 and 8 has hypotenuse 10.', 'Distance in coordinates, velocity components, and graphics all use this idea.', 'If legs are 3 and 4, what is the hypotenuse?', '5.', 'When does a^2 + b^2 = c^2 apply?', 'Right triangles', 'Every triangle no matter its angles'],
  [mathStages.geometry, 'Sine and Cosine', 'Core', 'Sine and cosine connect angles to vertical and horizontal components.', 'They are shadows of a rotating arrow.', 'At 30 degrees, sine tells the upward part and cosine tells the sideways part.', 'Projectile motion and computer graphics use trig components constantly.', 'Which component does cosine often represent on the unit circle?', 'The horizontal component.', 'What do sine and cosine help find?', 'Components connected to an angle', 'The number of objects in a list'],
  [mathStages.geometry, 'Radians and Circular Motion', 'Advanced', 'Radians measure angles by comparing arc length to radius.', 'A radian is an angle measured in circle lengths.', 'A full circle is 2 pi radians because circumference is 2 pi r.', 'Waves, rotations, and calculus use radians because they fit circular change naturally.', 'How many radians are in a half circle?', 'pi radians.', 'Why use radians?', 'They connect angles directly to circle geometry', 'They make angles unitless guesses'],
  [mathStages.calculus, 'Limits as Approaching', 'Advanced', 'A limit describes what a value approaches, even if it never lands exactly there.', 'A limit is watching the target a process moves toward.', 'As x gets closer to 0, sin(x)/x gets closer to 1.', 'Limits make derivatives precise and help model continuous physical change.', 'If values get closer to 5, what is the limit?', 'The limit is 5.', 'What does a limit describe?', 'What a quantity approaches', 'Only values that are impossible'],
  [mathStages.calculus, 'Instantaneous Rate', 'Advanced', 'Instantaneous rate measures change at a single moment.', 'It is the speedometer reading for any changing function.', 'A car may average 50 mph but be moving 63 mph at one instant.', 'Physics velocity and AI gradient updates rely on instant rates.', 'What graph feature gives instantaneous rate?', 'The slope of the tangent line.', 'What is instantaneous rate?', 'Rate of change at one moment', 'Total change over all time only'],
  [mathStages.calculus, 'Derivative Rules', 'Advanced', 'Derivative rules let you calculate rates of change efficiently.', 'Rules are shortcuts built from patterns in change.', 'The derivative of x^3 is 3x^2.', 'Engineering models and machine learning need derivatives without redrawing every tangent.', 'What is the derivative of x^2?', '2x.', 'Why use derivative rules?', 'To compute rates of change reliably', 'To avoid understanding change'],
  [mathStages.calculus, 'Composition and the Chain Rule', 'Advanced', 'When one function is nested inside another, the chain rule finds the derivative by multiplying the outer derivative by the inner derivative.', 'A composed function is a pipeline of transformations — the chain rule tracks how a tiny input change ripples through each stage to the final output.', 'For h(x) = (x^2 + 1)^3, let the inner function be g(x) = x^2 + 1 and the outer be f(u) = u^3. The derivative is f\'(g(x)) times g\'(x) = 3(x^2 + 1)^2 times 2x.', 'Backpropagation in neural networks is the chain rule applied at every layer: the gradient of the loss with respect to any weight equals the product of derivatives chained layer by layer from the output back to that weight — one multiplication per layer.', 'If h(x) = (3x)^2, what are the inner and outer functions and what is the derivative?', 'Inner: g(x) = 3x, outer: f(u) = u^2. Derivative = 2(3x) times 3 = 18x.', 'Why does backpropagation multiply gradients layer by layer rather than summing them?', 'Because the chain rule multiplies the outer derivative by the inner derivative at each nested composition step', 'Because all layers share the same gradient and contribute equally to the update'],
  [mathStages.calculus, 'Area and Accumulation', 'Advanced', 'Accumulation adds up tiny pieces to measure total change.', 'Area under a rate graph becomes the amount accumulated.', 'If speed is 10 m/s for 3 seconds, distance is 30 meters.', 'Physics uses accumulation for distance and work; AI uses sums across data.', 'What does area under velocity-time graph give?', 'Displacement or distance depending on direction.', 'What does accumulation measure?', 'Total built from many small contributions', 'Only the steepness of a line'],
  [mathStages.calculus, 'Differential Thinking', 'Advanced', 'Differential thinking studies tiny changes to understand a whole system.', 'A tiny nudge can reveal how sensitive a system is.', 'If increasing x slightly changes y a lot, the system is sensitive near that point.', 'Control systems, physics models, and AI optimization depend on sensitivity.', 'If a tiny input change causes a huge output change, what is high?', 'Sensitivity is high.', 'What does differential thinking focus on?', 'How small changes affect outcomes', 'Ignoring small changes entirely'],
  [mathStages.probability, 'Counting Outcomes', 'Foundation', 'Counting possible outcomes is the base of probability.', 'Before measuring chance, list what can happen.', 'A coin and a die have 2 x 6 = 12 combined outcomes.', 'Simulations and AI evaluation need clear outcome spaces.', 'How many outcomes for two coin flips?', '4 outcomes.', 'Why count outcomes?', 'To define the possibilities before assigning probabilities', 'To guarantee the best outcome'],
  [mathStages.probability, 'Probability as Long-Run Frequency', 'Core', 'Probability describes how often an event tends to happen over many trials.', 'Probability is a long-run pattern, not a single-event promise.', 'A fair coin has probability 0.5 for heads, but short streaks can happen.', 'AI confidence scores and physics measurements both live with uncertainty.', 'Can heads happen 4 times in a row with a fair coin?', 'Yes, but it is not the long-run average pattern.', 'What does probability describe?', 'Long-run likelihood under repeated conditions', 'A guarantee for the next trial'],
  [mathStages.probability, 'Expected Value', 'Core', 'Expected value is the probability-weighted average outcome.', 'It is the average result you would expect after many repeats.', 'A 20 percent chance of 10 dollars has expected value 2 dollars.', 'Decision systems and AI agents compare uncertain choices using expected outcomes.', 'What is EV of 50 percent chance at 8 points?', '4 points.', 'What is expected value?', 'Probability-weighted average outcome', 'The biggest possible prize'],
  [mathStages.probability, 'Mean, Median, and Spread', 'Core', 'Statistics summarize a data set with center and variation.', 'Center tells where data clusters; spread tells how scattered it is.', 'Scores 80, 82, 98 have mean about 86.7 but a high value pulls it upward.', 'AI datasets need summaries to spot skew, noise, and outliers.', 'If one huge value appears, which center can shift strongly?', 'The mean.', 'What does spread describe?', 'How far values vary from each other', 'Only the first value in a set'],
  [mathStages.probability, 'Correlation and Causation', 'Advanced', 'Correlation means two things move together; causation means one makes the other change.', 'Correlation is a clue, not a verdict.', 'Ice cream sales and sunburns rise together because hot weather affects both.', 'AI can detect correlations, but humans must test causal claims carefully.', 'Does correlation prove causation?', 'No. It suggests a relationship to investigate.', 'What is the causal trap?', 'Assuming movement together proves one causes the other', 'Using data before asking a question'],
  [mathStages.linear, 'Vectors as Arrows', 'Core', 'A vector represents magnitude and direction or a list of components.', 'A vector is an arrow with coordinates.', 'The vector [3, 4] means 3 right and 4 up, with length 5.', 'Forces, velocities, image pixels, and AI features can all be vectors.', 'What direction is [0, -2]?', 'Straight down.', 'What can a vector represent?', 'A quantity with components or direction', 'Only a single unchanging word'],
  [mathStages.linear, 'Vector Addition', 'Core', 'Vector addition combines components to find a net effect.', 'Add arrows tip-to-tail or add matching components.', '[2, 1] + [3, -4] = [5, -3].', 'Net force and combined movement in games both use vector addition.', 'What is [1, 2] + [4, 0]?', '[5, 2].', 'How do you add vectors by components?', 'Add corresponding components', 'Add only the biggest component'],
  [mathStages.linear, 'Dot Product', 'Advanced', 'The dot product measures how much two vectors point in the same direction.', 'It is a direction agreement score.', 'A force in the same direction as motion does positive work.', 'Physics work, search similarity, and AI embeddings use dot products.', 'If vectors are perpendicular, what is their dot product?', 'Zero.', 'What does a dot product reveal?', 'Directional alignment between vectors', 'Only the length of the first vector'],
  [mathStages.linear, 'Matrices as Transformations', 'Advanced', 'A matrix can transform vectors by rotating, scaling, or mixing components.', 'A matrix is a machine for reshaping space or data.', 'A scaling matrix can double every x-coordinate while leaving y unchanged.', 'Graphics, physics simulations, and neural networks use matrix transformations.', 'What can a rotation matrix do?', 'Turn vectors by an angle.', 'What is one role of a matrix?', 'Transform vectors or organize relationships', 'Store only one number'],
  [mathStages.linear, 'Matrix Multiplication', 'Advanced', 'To multiply two matrices, each output entry is the dot product of a row from the first matrix with a column from the second.', 'Matrix multiplication is systematic dot-producting: each row of A meets each column of B to produce one entry of the result.', 'For 2x2 matrices, the top-left entry of A×B is row 1 of A dotted with column 1 of B: if row is [1,2] and column is [3,4], the entry is 1×3 + 2×4 = 11.', 'Neural network forward passes multiply input vectors by weight matrices at every layer, and transformer attention computes Q×K^T — a matrix multiplication of query and key matrices that produces the full attention score grid.', 'Can you multiply a 2×3 matrix by a 3×2 matrix, and what shape is the result?', 'Yes. The inner dimensions match (both 3), and the result is a 2×2 matrix.', 'If A×B = C, does B×A always equal C?', 'Not necessarily — matrix multiplication is generally not commutative', 'Yes, because numbers always multiply in any order'],
  [mathStages.linear, 'Transpose and Linear Independence', 'Advanced', 'Transposing a matrix swaps its rows and columns; linear independence means no vector in a set can be written as a combination of the others.', 'A transpose is a rotation across the diagonal — rows become columns. Independence means each vector adds a genuinely new direction that the others cannot reach.', 'If A = [[1,2],[3,4]], then A^T = [[1,3],[2,4]]. Multiplying A×A^T always yields a square symmetric matrix — the structure behind covariance matrices and attention score normalization.', 'Transformer attention computes Q×K^T where K^T is the transpose of the key matrix, making transpose a core operation in every modern language model. Linear independence determines whether a model\'s learned feature vectors are genuinely diverse or whether some are redundant combinations of others.', 'If A is a 3×4 matrix, what is the shape of A^T?', '4×3, because transposing swaps the row count and column count.', 'What does linear independence mean for a set of vectors?', 'No vector in the set can be written as a combination of the others', 'All vectors point in exactly opposite directions from each other'],
  [mathStages.linear, 'Systems in Matrix Form', 'Advanced', 'Matrices can package many linear equations into one organized structure.', 'A matrix is a spreadsheet version of a system of equations.', 'Two equations with x and y can be written as a coefficient matrix times a vector.', 'Engineering solvers and AI training use matrix systems for many variables.', 'Why put equations in a matrix?', 'To solve and organize many relationships efficiently.', 'What does matrix form help with?', 'Handling many linked linear equations', 'Avoiding all variables'],
  [mathStages.optimization, 'Error and Loss', 'Advanced', 'Loss measures how far a prediction is from the desired answer.', 'Loss is a score for wrongness.', 'If the target is 10 and prediction is 7, the error has size 3.', 'AI training uses loss to decide what needs improvement.', 'If predictions improve, what should happen to loss?', 'Loss should usually decrease.', 'What does loss measure?', 'Prediction error', 'How pretty a graph looks'],
  [mathStages.optimization, 'Gradient Direction', 'Advanced', 'A gradient points in the direction of fastest increase, so moving opposite it can reduce loss.', 'Imagine a hill: the gradient points uphill, and learning often steps downhill.', 'If loss increases to the right, a model should adjust left to reduce it.', 'Calculus turns AI training into a guided search instead of random guessing.', 'To reduce loss, which way do you move relative to the gradient?', 'Usually opposite the gradient.', 'What does a gradient show?', 'Direction of fastest increase', 'A final guarantee of correctness'],
  [mathStages.optimization, 'Learning Rate', 'Advanced', 'Learning rate controls how big each optimization step is.', 'It is the stride length while walking downhill.', 'A tiny learning rate is slow; a huge one can jump past the best point.', 'AI models need learning rates that balance speed and stability.', 'What can happen if learning rate is too large?', 'Training can overshoot and become unstable.', 'What does learning rate control?', 'Step size during learning', 'The number of quiz choices'],
  [mathStages.optimization, 'Normalization', 'Advanced', 'Normalization rescales data so values are easier to compare and learn from.', 'It puts different measurements onto a fair playing field.', 'Height in meters and income in dollars have very different scales, so rescaling can help models.', 'Statistics and AI pipelines often normalize inputs before training.', 'Why normalize features before AI training?', 'So one large-scale feature does not dominate unfairly.', 'What does normalization do?', 'Rescales data for comparison or learning', 'Deletes all variation'],
  [mathStages.optimization, 'Model Fit and Generalization', 'Advanced', 'A model should fit useful patterns without merely memorizing examples.', 'Good learning is understanding the rule, not copying the worksheet.', 'A curve that hits every noisy training point may fail on new data.', 'Statistics, algorithms, and AI all care about performance on unseen cases.', 'What is overfitting?', 'Memorizing training noise instead of learning a useful pattern.', 'What is generalization?', 'Working well on new examples', 'Scoring perfectly by memorizing noise'],
];

const physicsSpecs = [
  [physicsStages.measurement, 'Units as Meaning', 'Foundation', 'Units tell what a number physically means.', 'A unit is the label that connects a number to the real world.', '5 seconds and 5 meters are completely different quantities.', 'Math calculations and programs must preserve units to avoid dangerous mistakes.', 'Can 10 meters be added directly to 3 seconds?', 'No. They are different kinds of quantities.', 'What do units provide?', 'Physical meaning for numbers', 'A way to make numbers decorative'],
  [physicsStages.measurement, 'Significant Figures', 'Foundation', 'Significant figures show how precise a measurement is.', 'Precision is how fine the ruler marks are.', 'A value of 2.0 m says more precision than 2 m.', 'Sensors and AI data both carry limits in precision.', 'Does 3.40 show more precision than 3.4?', 'Yes. The trailing zero communicates measured precision.', 'What do significant figures communicate?', 'Measurement precision', 'The importance of a topic'],
  [physicsStages.measurement, 'Estimation in Science', 'Foundation', 'Estimation checks whether a physical claim is reasonable.', 'Estimation is a quick reality test.', 'A classroom is more likely 10 meters wide than 1000 meters wide.', 'Engineers and AI modelers estimate before trusting detailed outputs.', 'Is a walking speed of 100 m/s reasonable?', 'No. That is far too fast for walking.', 'Why estimate in physics?', 'To catch impossible or unreasonable claims', 'To avoid measuring anything ever'],
  [physicsStages.measurement, 'Experimental Variables', 'Foundation', 'Experiments separate what you change, what you measure, and what you keep controlled.', 'A fair experiment changes one knob at a time.', 'To test ramp angle, keep cart mass and surface the same.', 'CS testing uses the same logic when isolating bugs.', 'What should you do with other conditions while testing one variable?', 'Keep them controlled.', 'What is a controlled variable?', 'A factor kept the same during a test', 'The answer you hope to get'],
  [physicsStages.measurement, 'Uncertainty and Error Bars', 'Core', 'Every measurement has uncertainty, and error bars show a reasonable range.', 'An error bar is a honesty marker on a measurement.', 'A length of 10.0 plus or minus 0.2 cm means values near that range are plausible.', 'AI predictions and sensor readings should communicate uncertainty too.', 'If two error bars overlap, should you be cautious comparing them?', 'Yes. The difference may not be meaningful.', 'What do error bars show?', 'A range of measurement uncertainty', 'A mistake that ruins the experiment'],
  [physicsStages.motion, 'Position and Reference Frames', 'Foundation', 'Position depends on the reference point you choose.', 'A reference frame is the coordinate system for a physical story.', 'A car can be 10 m east of a sign but 30 m west of a building.', 'Coordinate systems connect physics, graphing, and game worlds.', 'Can the same object have different position values in different frames?', 'Yes, if the reference points differ.', 'What is a reference frame?', 'A viewpoint or coordinate system for measuring motion', 'A force that changes speed'],
  [physicsStages.motion, 'Average Velocity', 'Foundation', 'Average velocity is displacement divided by time.', 'It is the overall slope of a trip.', 'Moving 20 m east in 5 s gives average velocity 4 m/s east.', 'Slope in math becomes velocity in physics.', 'If displacement is 30 m in 10 s, what is average velocity?', '3 m/s.', 'What does average velocity use?', 'Displacement divided by time', 'Total path color divided by mass'],
  [physicsStages.motion, 'Acceleration', 'Core', 'Acceleration is the rate velocity changes.', 'Acceleration is what your body feels when motion changes.', 'Going from 0 to 12 m/s in 4 s gives acceleration 3 m/s^2.', 'Derivatives and simulations both represent changing velocity.', 'If velocity changes by 10 m/s in 2 s, what is acceleration?', '5 m/s^2.', 'What does acceleration measure?', 'Change in velocity over time', 'Location without time'],
  [physicsStages.motion, 'Free Fall', 'Core', 'In free fall near Earth, gravity accelerates objects downward at about 9.8 m/s^2.', 'Gravity keeps adding downward velocity each second.', 'After 2 seconds from rest, an object falls at about 19.6 m/s downward, ignoring air resistance.', 'Calculus and code simulations can model free fall step by step.', 'Does mass change free-fall acceleration without air resistance?', 'No. Objects share the same gravitational acceleration.', 'What is free-fall acceleration near Earth?', 'About 9.8 m/s^2 downward', 'Zero for heavy objects'],
  [physicsStages.motion, 'Projectile Components', 'Core', 'Projectile motion splits into horizontal and vertical components.', 'A projectile is two simpler motions happening at once.', 'Horizontal velocity stays steady while vertical velocity changes due to gravity.', 'Trig and vectors explain the projectile lab.', 'Which component does gravity directly change?', 'The vertical component.', 'Why split projectile motion?', 'To analyze horizontal and vertical effects separately', 'To remove gravity from the problem'],
  [physicsStages.forces, 'Inertia', 'Foundation', 'Inertia is an objects resistance to changes in motion.', 'Mass is stubbornness against acceleration.', 'A bowling ball is harder to start or stop than a tennis ball.', 'Robotics and vehicle safety depend on inertia.', 'Which has more inertia, a truck or a skateboard?', 'The truck.', 'What does inertia resist?', 'Changes in motion', 'Changes in color'],
  [physicsStages.forces, 'Net Force', 'Foundation', 'Net force is the combined effect of all forces on an object.', 'Forces can cancel or reinforce like tug-of-war teams.', '10 N right and 4 N left gives net force 6 N right.', 'Vector addition from math is how forces combine.', 'If equal forces pull opposite ways, what is net force?', 'Zero.', 'What is net force?', 'The vector sum of all forces', 'The largest force only every time'],
  [physicsStages.forces, 'Newton Second Law', 'Core', 'Newton second law connects net force, mass, and acceleration.', 'Force is what changes motion; mass controls how much change you get.', 'A 5 kg object with 2 m/s^2 acceleration needs 10 N net force.', 'Algebra and simulation use F = ma constantly.', 'If force doubles and mass stays, what happens to acceleration?', 'It doubles.', 'What does F = ma mean?', 'Net force equals mass times acceleration', 'Force equals motion without mass'],
  [physicsStages.forces, 'Friction Models', 'Core', 'Friction resists sliding and depends on surface interaction.', 'Friction is the contact surface pushing back against slipping.', 'A rough floor needs more force to slide a box than a smooth floor.', 'Constraints in code and inequalities in math describe friction limits.', 'What happens to sliding if friction increases?', 'Sliding becomes harder.', 'What does friction oppose?', 'Relative sliding or attempted sliding', 'All motion in every direction equally'],
  [physicsStages.forces, 'Normal Force', 'Core', 'The normal force is a support force perpendicular to a surface.', 'A table pushes back upward so objects do not fall through it.', 'A book at rest on a table has weight downward and normal force upward.', 'Force diagrams use vectors and constraints together.', 'On a flat table, which direction is normal force?', 'Upward, perpendicular to the table.', 'What is normal force?', 'A support force perpendicular to a surface', 'A force that always points sideways'],
  [physicsStages.energy, 'Work', 'Core', 'Work transfers energy when a force acts through a distance.', 'Work is energy moved by a push or pull over motion.', 'Pushing 8 N for 3 m does 24 J of work if aligned.', 'Dot products in math describe how much force aligns with motion.', 'If there is force but no displacement, what is work?', 'Zero mechanical work.', 'When is mechanical work done?', 'When force causes displacement in its direction', 'Whenever an object has mass'],
  [physicsStages.energy, 'Kinetic Energy', 'Core', 'Kinetic energy is energy of motion.', 'Moving objects carry energy because stopping them takes work.', 'A faster cart has much more kinetic energy because speed is squared.', 'Quadratic math appears in energy and safety design.', 'If speed doubles, kinetic energy changes how?', 'It becomes four times larger.', 'What is kinetic energy?', 'Energy due to motion', 'Energy due only to height'],
  [physicsStages.energy, 'Potential Energy', 'Core', 'Potential energy is stored energy due to position or configuration.', 'It is energy waiting because of where something is or how it is arranged.', 'A lifted book stores gravitational potential energy.', 'Graphs and simulations track energy transformations.', 'What happens to gravitational potential energy when height increases?', 'It increases.', 'What is potential energy?', 'Stored energy due to position or configuration', 'Random energy with no source'],
  [physicsStages.energy, 'Conservation of Energy', 'Core', 'Energy changes form but total energy is conserved in a closed system.', 'Energy is a budget that can move between accounts.', 'A roller coaster trades height energy for motion energy.', 'AI optimization can improve energy use but cannot break conservation.', 'Where does some energy go when friction acts?', 'Into thermal energy.', 'What does energy conservation say?', 'Total energy is preserved in a closed system', 'Energy disappears whenever motion stops'],
  [physicsStages.energy, 'Momentum Conservation', 'Core', 'Momentum is conserved in isolated collisions and interactions.', 'Momentum is motion-accounting for systems.', 'Two carts colliding exchange momentum, but total momentum stays the same if outside forces are negligible.', 'Vector math and game physics both use momentum conservation.', 'If no outside force acts, what happens to total momentum?', 'It stays constant.', 'When is momentum conserved?', 'In an isolated system with no net external force', 'Only when objects are not moving'],
  [physicsStages.waves, 'Oscillation', 'Core', 'Oscillation is repeated motion around an equilibrium.', 'It is a system overshooting and returning again and again.', 'A mass on a spring moves back and forth around its resting point.', 'Loops in code can simulate oscillating systems.', 'What point does an oscillator move around?', 'Equilibrium.', 'What is oscillation?', 'Repeated motion around equilibrium', 'One-way motion forever'],
  [physicsStages.waves, 'Frequency and Period', 'Core', 'Frequency is cycles per second; period is seconds per cycle.', 'They are two ways to describe rhythm.', 'A 2 Hz wave has period 0.5 seconds.', 'Audio processing and trig functions rely on frequency.', 'If frequency increases, what happens to period?', 'Period decreases.', 'How are frequency and period related?', 'They are reciprocals', 'They are always equal'],
  [physicsStages.waves, 'Amplitude', 'Foundation', 'Amplitude measures the size of an oscillation.', 'Amplitude is how far the wave swings from center.', 'A louder sound often has larger pressure-wave amplitude.', 'Signals in CS and physics both track amplitude.', 'If amplitude doubles, what visual change occurs?', 'The wave gets taller from its center line.', 'What does amplitude measure?', 'Size of a wave or oscillation', 'Number of cycles per second'],
  [physicsStages.waves, 'Resonance', 'Advanced', 'Resonance happens when a system is driven near its natural frequency.', 'Push at the right rhythm and the motion grows.', 'A swing goes higher when pushed in time with its motion.', 'Engineering and audio software must handle resonance carefully.', 'What happens when driving frequency matches natural frequency?', 'Oscillation can grow strongly.', 'What is resonance?', 'Strong response near natural frequency', 'Motion with no repeating pattern'],
  [physicsStages.waves, 'Wave Interference', 'Advanced', 'Waves can add together or cancel depending on alignment.', 'Interference is wave arithmetic in space.', 'Two crests combine into a bigger crest; a crest and trough can cancel.', 'Noise cancellation and signal processing use interference.', 'What happens when equal crest meets equal trough?', 'They cancel strongly.', 'What does interference describe?', 'How overlapping waves combine', 'A force that only affects batteries'],
  [physicsStages.electricity, 'Electric Charge', 'Foundation', 'Electric charge is a property that creates electric forces.', 'Charge is the source of electrical push and pull.', 'Like charges repel and opposite charges attract.', 'Electronic circuits and sensors depend on charge behavior.', 'Do two negative charges attract or repel?', 'They repel.', 'What do like charges do?', 'Repel each other', 'Always become neutral instantly'],
  [physicsStages.electricity, 'Voltage', 'Core', 'Voltage is electric potential difference, like electrical pressure.', 'Voltage is the push available per charge.', 'A 9 V battery provides more push per charge than a 1.5 V cell.', 'Computers rely on voltage levels to represent signals.', 'If voltage increases across same resistance, what happens to current?', 'Current increases.', 'What is voltage like?', 'Electric push or potential difference', 'The number of wires in a circuit'],
  [physicsStages.electricity, 'Current', 'Core', 'Current is the rate electric charge flows.', 'Current is traffic flow for charge.', '2 amps means 2 coulombs of charge pass each second.', 'Current limits affect circuits that power processors and robots.', 'What unit measures current?', 'Ampere.', 'What does current measure?', 'Rate of charge flow', 'Stored program instructions'],
  [physicsStages.electricity, 'Resistance and Ohms Law', 'Core', 'Resistance limits current, and Ohms law relates voltage, current, and resistance.', 'Resistance is a narrow pipe for charge flow.', 'With 12 V and 4 ohms, current is 3 A.', 'Algebra turns circuit relationships into solvable equations.', 'If resistance doubles at same voltage, current does what?', 'It halves.', 'What is Ohms law?', 'V = IR', 'F = ma'],
  [physicsStages.electricity, 'Series and Parallel Circuits', 'Core', 'Series circuits share one path; parallel circuits provide multiple paths.', 'Series is one road; parallel is several roads side by side.', 'Two bulbs in series both go out if the path breaks.', 'Circuit design mirrors graph paths in computer science.', 'Which circuit type has multiple paths?', 'Parallel.', 'What distinguishes parallel circuits?', 'Multiple current paths', 'No voltage anywhere'],
  [physicsStages.systems, 'Free-Body Diagrams', 'Core', 'A free-body diagram isolates one object and shows all forces on it.', 'It is a force inventory for one object.', 'For a falling ball, draw weight downward and air resistance upward if included.', 'Diagrams turn physical situations into vector equations.', 'Why isolate one object?', 'To clearly account for forces acting on it.', 'What does a free-body diagram show?', 'Forces acting on one chosen object', 'Every object in the universe at once'],
  [physicsStages.systems, 'Constraints and Degrees of Freedom', 'Advanced', 'Constraints limit possible motion; degrees of freedom count how motion can vary.', 'Constraints are rules that remove options.', 'A bead on a wire can move along the wire but not freely in all directions.', 'Robotics and game physics model constraints explicitly.', 'What does a rigid track do to motion?', 'It constrains the object to the track.', 'What do constraints do?', 'Limit allowed motion', 'Create energy from nothing'],
  [physicsStages.systems, 'Equilibrium', 'Core', 'Equilibrium occurs when competing effects balance.', 'Nothing changes overall because pushes cancel or rates match.', 'A book at rest has upward normal force balancing downward weight.', 'Solving systems of equations often finds equilibrium states.', 'If net force is zero, can an object be in equilibrium?', 'Yes, for translational motion.', 'What is equilibrium?', 'A balanced state with no net change', 'A state where forces are missing'],
  [physicsStages.systems, 'Feedback Loops', 'Advanced', 'Feedback occurs when a systems output affects its future input.', 'A thermostat watches results and adjusts behavior.', 'If a room is too cold, heat turns on until the target is reached.', 'AI control systems and programs use feedback to self-correct.', 'What does negative feedback usually do?', 'Reduce deviation from a target.', 'What is feedback?', 'Output influencing future input', 'A graph with no axes'],
  [physicsStages.systems, 'Model Assumptions', 'Advanced', 'A model is useful only within the assumptions that make it simpler.', 'A model is a map, not the territory.', 'Ignoring air resistance works for some projectiles but fails for feathers.', 'AI and simulations both fail when assumptions do not match reality.', 'Why state assumptions?', 'So you know when the model can be trusted.', 'What is a model assumption?', 'A simplifying condition used to reason', 'A fact that never needs checking'],
  [physicsStages.bridges, 'Numerical Simulation', 'Advanced', 'Numerical simulation approximates change step by step.', 'A simulation is a flipbook of small updates.', 'Update velocity from acceleration, then position from velocity, many times.', 'CS turns physics equations into running models.', 'What happens if time steps are too large?', 'The simulation can become inaccurate or unstable.', 'What is numerical simulation?', 'Step-by-step approximation of a changing system', 'A perfect copy of reality every time'],
  [physicsStages.bridges, 'Sensors and Data', 'Core', 'Sensors convert physical quantities into data.', 'A sensor is a translator from world behavior to numbers.', 'A thermometer turns molecular motion into a temperature reading.', 'AI systems often begin with sensor data from the physical world.', 'Can sensor data include noise?', 'Yes. Measurements are imperfect.', 'What do sensors do?', 'Turn physical quantities into data', 'Remove the need for measurement'],
  [physicsStages.bridges, 'Control Systems', 'Advanced', 'Control systems choose actions to move a system toward a goal.', 'Control is steering with feedback.', 'Cruise control adjusts throttle to maintain speed.', 'Robotics combines physics models, algorithms, and AI control.', 'What does a controller compare?', 'Current state and target state.', 'What is a control system for?', 'Choosing actions to reach or maintain a goal', 'Making systems ignore feedback'],
  [physicsStages.bridges, 'Digital Twins', 'Advanced', 'A digital twin is a computational model of a real physical system.', 'It is a live practice version of a real machine or process.', 'A factory robot can have a simulated twin for testing changes safely.', 'Digital twins connect physics, data, and software engineering.', 'Why test on a digital twin?', 'To explore changes before risking the real system.', 'What is a digital twin?', 'A computational model linked to a real system', 'A duplicate file with no behavior'],
  [physicsStages.bridges, 'Physics-Informed AI', 'Advanced', 'Physics-informed AI uses physical laws to guide learning.', 'It gives a model guardrails from reality.', 'A model predicting motion can be penalized for violating conservation laws.', 'This bridges equations, data, and machine learning.', 'Why add physics to AI training?', 'To make predictions more realistic and data-efficient.', 'What does physics-informed AI use?', 'Physical laws as learning constraints', 'Random guesses without equations'],
];

const csSpecs = [
  [csStages.thinking, 'Decomposing Problems', 'Foundation', 'Decomposition breaks a large problem into smaller solvable parts.', 'A big task becomes a checklist of smaller tasks.', 'To build a quiz app, separate questions, answers, scoring, and display.', 'Science models also break systems into variables and interactions.', 'What should you do first with an overwhelming task?', 'Split it into smaller parts.', 'What is decomposition?', 'Breaking a problem into manageable pieces', 'Doing every step at once'],
  [csStages.thinking, 'Patterns and Abstraction', 'Foundation', 'Abstraction keeps the important pattern and hides unnecessary detail.', 'It is a useful simplification.', 'A map ignores individual leaves but shows roads you need.', 'Math functions and physics models are abstractions too.', 'Why hide detail in an abstraction?', 'To focus on what matters for the task.', 'What is abstraction?', 'A simplified representation of important structure', 'A refusal to be precise'],
  [csStages.thinking, 'Algorithms as Recipes', 'Foundation', 'An algorithm is a precise method for solving a class of problems.', 'It is a recipe that works for many inputs.', 'Long division is an algorithm for dividing numbers.', 'Physics procedures and math methods can become algorithms.', 'Can an algorithm handle many inputs?', 'Yes, if its steps are general.', 'What is an algorithm?', 'A step-by-step problem-solving method', 'A single lucky answer'],
  [csStages.thinking, 'State and Change', 'Foundation', 'State is the current information a system remembers.', 'State is the snapshot before the next step.', 'A game stores player position, score, and health as state.', 'Physics simulations store position and velocity as state.', 'If position updates each frame, what changed?', 'The program state changed.', 'What is state?', 'Remembered information at a moment', 'A line of text with no effect'],
  [csStages.thinking, 'Inputs, Process, Outputs', 'Foundation', 'Computational systems transform inputs into outputs through a process.', 'It is the same machine idea as a function.', 'A calculator takes numbers and an operation, then returns a result.', 'AI models and physics formulas both fit this input-process-output pattern.', 'What is the output of a weather app?', 'A forecast or weather information.', 'What does IPO describe?', 'Input, process, and output', 'Only the final screen color'],
  [csStages.fundamentals, 'Variables in Programs', 'Foundation', 'Program variables store values that code can read and change.', 'A variable is a labeled drawer in memory.', 'let count = 0 stores a number that can increase later.', 'Math variables represent quantities; program variables hold current values.', 'What happens when count = count + 1?', 'The stored count increases by one.', 'What is a program variable?', 'A named place for stored data', 'A permanent law of nature'],
  [csStages.fundamentals, 'Data Types', 'Foundation', 'Data types describe what kind of value a program is using.', 'Type is the shape of data.', '42 is a number, "42" is text, and true is a boolean.', 'AI datasets must keep types clear to avoid bad training data.', 'Can text "5" behave differently from number 5?', 'Yes. They are different types.', 'Why do data types matter?', 'They control valid operations on values', 'They only change font style'],
  [csStages.fundamentals, 'Conditionals', 'Foundation', 'Conditionals let programs choose a branch based on a true-or-false test.', 'They are decision gates.', 'If lives === 0, end the game; otherwise keep playing.', 'Physics simulations use conditionals for collisions and boundaries.', 'If temperature is below freezing, which branch should run?', 'The freezing warning branch.', 'What does a conditional do?', 'Chooses code based on a condition', 'Repeats code automatically forever'],
  [csStages.fundamentals, 'Loops', 'Foundation', 'Loops repeat instructions until a count or condition says stop.', 'A loop is controlled repetition.', 'For each score in a list, add it to the total.', 'Simulations loop through time steps; AI trains over many examples.', 'What risk comes from a loop with no stopping condition?', 'An infinite loop.', 'What does a loop do?', 'Repeats a block of instructions', 'Stores a single image pixel'],
  [csStages.fundamentals, 'Functions in Code', 'Foundation', 'A function packages reusable logic behind a name.', 'It is a small machine inside a program.', 'area(width, height) can return width * height.', 'Math functions and code functions both connect inputs to outputs.', 'What does return usually provide?', 'The functions output value.', 'Why write functions?', 'To reuse and organize logic', 'To make every variable global'],
  [csStages.fundamentals, 'Recursion', 'Core', 'A recursive function solves a problem by calling itself with a smaller input until a base case stops the chain.', 'Recursion is a mirror that shows a smaller version of the same problem, getting simpler each step until it becomes trivial.', 'factorial(3) calls factorial(2), which calls factorial(1), which returns 1 — results then multiply back: 1, 2, 6.', 'Graph traversal and tree search work by visiting a node then recursively visiting each neighbor — the same structure backpropagation uses to visit every parent in a computational graph in reverse topological order.', 'In factorial(n) = n × factorial(n-1), what stops the chain?', 'The base case factorial(1) = 1, because without it the function calls itself forever and the call stack overflows.', 'What happens if a recursive function has no base case?', 'It calls itself indefinitely until the call stack overflows', 'It finds the correct answer after enough recursive steps'],
  [csStages.structures, 'Arrays', 'Foundation', 'An array stores an ordered list of values.', 'An array is a numbered row of boxes.', 'scores[0] accesses the first score in many languages.', 'Vectors in math resemble arrays of numbers.', 'If an array has 5 items, what does length often return?', '5.', 'What is an array good for?', 'Ordered collections of values', 'Only one true-false decision'],
  [csStages.structures, 'Objects and Records', 'Core', 'Objects group related named values.', 'An object is a labeled index card.', 'student = { name: "Kai", grade: 9 } stores related facts.', 'Physics objects can store mass, position, and velocity.', 'Why use an object for a student?', 'It keeps related fields together.', 'What does an object store?', 'Named properties and values', 'Only repeated steps'],
  [csStages.structures, 'Stacks', 'Core', 'A stack is last-in, first-out storage.', 'It is a pile: the last item placed is first removed.', 'Undo history often behaves like a stack.', 'Forces can stack conceptually, but CS stacks have a strict access rule.', 'Which item leaves a stack first?', 'The most recently added item.', 'What is stack order?', 'Last in, first out', 'Smallest value first always'],
  [csStages.structures, 'Queues', 'Core', 'A queue is first-in, first-out storage.', 'It is a waiting line.', 'Print jobs are often handled in queue order.', 'Physics event simulations can process scheduled events in queues.', 'Who is served first in a queue?', 'The earliest item added.', 'What is queue order?', 'First in, first out', 'Last in, first out'],
  [csStages.structures, 'Graphs', 'Core', 'A graph represents nodes connected by edges.', 'A graph is a network map.', 'Cities can be nodes and roads can be edges.', 'Circuits, social networks, molecules, and AI knowledge graphs use graph ideas.', 'What would roads be in a city graph?', 'Edges.', 'What does a graph model?', 'Connected relationships', 'Only a straight line of numbers'],
  [csStages.algorithms, 'Linear Search', 'Foundation', 'Linear search checks items one by one until it finds a match.', 'It is looking through a shelf from left to right.', 'To find 7 in [3, 5, 7], check 3, then 5, then 7.', 'Data analysis and sensor scans often begin with simple search.', 'Worst case, how many items might linear search check?', 'All of them.', 'What is linear search?', 'Checking items one at a time', 'Jumping directly to the middle every time'],
  [csStages.algorithms, 'Binary Search', 'Core', 'Binary search halves the search space each step, but needs sorted data.', 'It is the number-guessing game strategy.', 'In a sorted list, compare the middle and discard half.', 'Logarithms explain why binary search scales well.', 'What condition does binary search need?', 'Sorted data.', 'Why is binary search fast?', 'It cuts the remaining possibilities in half', 'It checks every item twice'],
  [csStages.algorithms, 'Sorting', 'Core', 'Sorting rearranges data into a useful order.', 'Sorting turns a messy shelf into an organized shelf.', 'Sorting names alphabetically makes lookup easier.', 'Measurement data and AI preprocessing often need sorting.', 'Why sort before searching sometimes?', 'Sorted data enables faster strategies like binary search.', 'What does sorting do?', 'Reorders data by a rule', 'Deletes data that looks hard'],
  [csStages.algorithms, 'Big-O Growth', 'Core', 'Big-O describes how work grows as input size grows.', 'It is a scaling label.', 'O(n^2) can become painful when n gets large.', 'The complexity lab turns this math into a visible curve.', 'Which grows faster for large n: n or n^2?', 'n^2.', 'What does Big-O focus on?', 'Growth rate with input size', 'Exact milliseconds on one laptop'],
  [csStages.algorithms, 'Tradeoffs', 'Core', 'Algorithms often trade time, memory, simplicity, and accuracy.', 'Engineering is choosing which cost you can afford.', 'A cached result may use memory to save time.', 'Physics models also trade accuracy against computation.', 'Why might you use more memory?', 'To save time or avoid recomputation.', 'What is an algorithm tradeoff?', 'Choosing between competing costs', 'Proof that one method is best for everything'],
  [csStages.debugging, 'Reading Error Messages', 'Foundation', 'Error messages are clues about where and why a program failed.', 'An error message is a trail marker, not an insult.', 'Undefined variable means code used a name that has no value in scope.', 'Scientific debugging also starts by observing failure carefully.', 'Should you ignore the first useful error?', 'No. Read it carefully first.', 'What is an error message?', 'A clue about a failure', 'A random decoration in the terminal'],
  [csStages.debugging, 'Reproducing Bugs', 'Core', 'A reproducible bug can be triggered reliably, making it easier to fix.', 'A bug you can repeat is a bug you can study.', 'If clicking Save twice breaks data every time, you have a reproducible case.', 'Experiments in physics also need repeatable conditions.', 'Why reproduce a bug?', 'To observe and test fixes reliably.', 'What makes a bug reproducible?', 'Clear steps that trigger it again', 'A vague memory that something felt wrong'],
  [csStages.debugging, 'Unit Tests', 'Core', 'A unit test checks one small piece of code against an expected behavior.', 'It is a tiny experiment for a function.', 'Test that add(2, 3) returns 5.', 'Math examples and physics experiments both compare expected and actual results.', 'What should a unit test include?', 'Input and expected output.', 'What does a unit test check?', 'One focused behavior', 'The entire internet at once'],
  [csStages.debugging, 'Edge Cases', 'Core', 'Edge cases are unusual or boundary inputs where bugs often hide.', 'Edges are where assumptions crack.', 'An empty list, zero, and a very large number are common edge cases.', 'Physics models also fail at extremes if assumptions break.', 'Why test an empty list?', 'It may reveal assumptions about at least one item.', 'What is an edge case?', 'A boundary or unusual input', 'The average example only'],
  [csStages.debugging, 'Refactoring Safely', 'Advanced', 'Refactoring improves code structure without changing behavior.', 'It is cleaning the engine while keeping the car driving the same route.', 'Rename a confusing variable and run tests to ensure behavior stayed right.', 'Scientific models also get reorganized while preserving predictions.', 'What protects refactoring?', 'Tests and small changes.', 'What is refactoring?', 'Changing structure while preserving behavior', 'Changing behavior without noticing'],
  [csStages.systems, 'Memory and Storage', 'Core', 'Memory is fast temporary workspace; storage keeps data longer term.', 'Memory is a desk; storage is a filing cabinet.', 'A running app uses memory, while saved files live in storage.', 'AI models need both fast memory and durable datasets.', 'What disappears when a program closes unless saved?', 'Temporary memory state.', 'How do memory and storage differ?', 'Memory is fast and temporary; storage is persistent', 'They are always the same thing'],
  [csStages.systems, 'CPU and Instructions', 'Core', 'A CPU executes simple instructions very quickly.', 'The CPU is the worker following machine-level steps.', 'Adding numbers, moving data, and comparing values are basic CPU operations.', 'Physics circuits physically implement these instruction steps.', 'What does a CPU execute?', 'Instructions.', 'What is a CPU role?', 'Run instructions on data', 'Store every website permanently'],
  [csStages.systems, 'Operating Systems', 'Core', 'An operating system manages hardware, files, memory, and running programs.', 'It is the coordinator between apps and the machine.', 'The OS decides which program gets CPU time.', 'Robotics and scientific computing rely on OS resource management.', 'Who manages files and processes?', 'The operating system.', 'What does an OS manage?', 'Hardware resources and running programs', 'Only the app logo'],
  [csStages.systems, 'Networks', 'Core', 'Networks move data between computers using agreed protocols.', 'A network is a system of addresses and rules for messages.', 'A browser sends a request and a server returns a response.', 'Distributed sensors and AI services depend on networking.', 'What does a protocol define?', 'Rules for communication.', 'What is a network protocol?', 'An agreement for exchanging data', 'A local variable name'],
  [csStages.systems, 'Security Basics', 'Advanced', 'Security protects systems from unauthorized access and harmful behavior.', 'Security is designing for what could go wrong on purpose.', 'Hashing passwords is safer than storing raw passwords.', 'AI apps still need secure data handling and access control.', 'Why not store raw passwords?', 'A leak would reveal them directly.', 'What is security concerned with?', 'Protecting systems and data from misuse', 'Making buttons look larger'],
  [csStages.dataAi, 'Tables and Datasets', 'Foundation', 'A dataset is organized examples, often stored as rows and columns.', 'A table is a grid of observations and features.', 'A weather table might store date, temperature, humidity, and rain.', 'Statistics and AI both begin with structured data.', 'What does one row often represent?', 'One example or observation.', 'What is a dataset?', 'Organized examples for analysis', 'A single random number'],
  [csStages.dataAi, 'Features and Labels', 'Core', 'Features are inputs; labels are target answers used for supervised learning.', 'Features are clues, labels are what the model tries to predict.', 'For house prices, size and location are features; sale price is the label.', 'This is the function idea from math applied to data.', 'In image classification, what is the label?', 'The correct category name.', 'What is a feature?', 'An input used for prediction', 'The models final guarantee'],
  [csStages.dataAi, 'Training and Validation', 'Core', 'Training data teaches a model; validation data checks whether it learned usefully.', 'Do not grade the model only on the worksheet it practiced.', 'A model may fit training examples but fail on validation examples.', 'Statistics calls this generalization; AI engineering depends on it.', 'Why keep validation data separate?', 'To test performance on unseen examples.', 'What is validation data for?', 'Checking generalization', 'Making training longer automatically'],
  [csStages.dataAi, 'Loss Functions', 'Advanced', 'A loss function turns prediction error into a number to minimize.', 'Loss is a scoreboard for wrongness.', 'Squared error punishes larger mistakes more strongly.', 'Calculus and optimization use loss to update AI models.', 'If loss decreases on validation, what is likely happening?', 'The model is improving on held-out data.', 'What does a loss function do?', 'Measures prediction error for optimization', 'Stores raw images only'],
  [csStages.dataAi, 'Bias, Variance, and Data Quality', 'Advanced', 'Model quality depends on patterns, noise, and whether data represents the real task.', 'A model learns from the examples it sees, including their flaws.', 'A face model trained on narrow data can fail for people not represented.', 'Statistics and ethics both matter in AI systems.', 'What happens with biased training data?', 'The model can learn biased behavior.', 'Why care about data quality?', 'Bad data can produce bad or unfair predictions', 'More data always fixes every issue'],
  [csStages.software, 'User Stories', 'Foundation', 'A user story describes what someone needs to do and why.', 'It keeps software tied to human goals.', 'As a student, I want to filter lessons so I can find the right next topic.', 'Product design connects CS implementation to real learning needs.', 'Why include the reason in a user story?', 'It clarifies the goal behind the feature.', 'What does a user story capture?', 'A user need and purpose', 'Only the color palette'],
  [csStages.software, 'Stateful Interfaces', 'Core', 'Interactive apps keep state so the screen reflects user choices.', 'State is the memory behind the interface.', 'A selected quiz answer is state that changes feedback on screen.', 'This app stores learning progress in localStorage.', 'What happens when state changes?', 'The interface can update to match it.', 'What is UI state?', 'Remembered information that drives the interface', 'A fixed screenshot'],
  [csStages.software, 'Persistence with Local Storage', 'Core', 'Persistence keeps data after a page refresh or app restart.', 'Persistence is memory that survives leaving the room.', 'localStorage can save quiz answers in the browser.', 'Databases and AI apps use persistence for larger systems.', 'Why save progress persistently?', 'So work is not lost on refresh.', 'What does persistence mean?', 'Data survives beyond the current moment', 'Data disappears immediately'],
  [csStages.software, 'APIs and Boundaries', 'Core', 'An API is a boundary where software parts communicate through agreed inputs and outputs.', 'An API is a contract between systems.', 'A weather API accepts a location and returns forecast data.', 'Physics sensors, AI services, and apps often meet at APIs.', 'Why define an API clearly?', 'So systems can work together without knowing every internal detail.', 'What is an API?', 'An agreed interface between software parts', 'A random private variable'],
  [csStages.software, 'Shipping and Iteration', 'Advanced', 'Real software improves through cycles of building, testing, feedback, and revision.', 'Shipping is learning from reality, then improving.', 'Release a small feature, watch where users struggle, then refine it.', 'Engineering, science, and AI all improve through measured iteration.', 'Why ship small improvements?', 'To learn quickly and reduce risk.', 'What is iteration?', 'Repeated improvement based on feedback', 'One perfect attempt with no testing'],
];

const languageSpecs = [
  [languageStages.foundations, 'Nouns Name Things', 'Foundation', 'A noun names a person, place, thing, or idea.', 'A noun is a label for something your sentence is talking about.', 'In "The robot measured temperature," robot and temperature are nouns.', 'Clear nouns help math, physics, and code identify the objects and quantities in a problem.', 'In "The sensor recorded motion," which words are nouns?', 'Sensor and motion are nouns because they name things or ideas.', 'What does a noun do?', 'Names a person, place, thing, or idea', 'Shows how fast an action happens'],
  [languageStages.foundations, 'Verbs Show Action or State', 'Foundation', 'A verb tells what happens or what something is.', 'A verb is the engine of a sentence.', 'In "The model predicts a value," predicts is the verb.', 'Physics problems depend on verbs like moves, accelerates, collides, and balances.', 'In "The force changes motion," which word is the verb?', 'Changes is the verb because it tells what force does.', 'What does a verb usually show?', 'Action, change, or state of being', 'Only the name of an object'],
  [languageStages.foundations, 'Adjectives Add Specific Detail', 'Foundation', 'An adjective describes a noun so the reader knows which kind, how many, or what quality.', 'An adjective is a zoom lens for a noun.', 'In "a rough surface," rough tells what kind of surface.', 'Precise adjectives make observations and bug reports easier to trust.', 'Why is "the red wire" clearer than "the wire"?', 'Red narrows which wire you mean.', 'What does an adjective modify?', 'A noun', 'A whole algorithm every time'],
  [languageStages.foundations, 'Adverbs Describe Actions', 'Foundation', 'An adverb describes a verb, adjective, or another adverb.', 'An adverb tells how, when, where, or how much.', 'In "the graph rises quickly," quickly describes rises.', 'Rates, trends, and careful instructions often depend on adverb-like precision.', 'In "increase slowly," what does slowly explain?', 'How the increase happens.', 'What question can an adverb answer?', 'How, when, where, or how much', 'Which noun is being named'],
  [languageStages.foundations, 'Sentence Structure', 'Foundation', 'A complete sentence usually has a subject and a predicate.', 'A sentence is a tiny thought with someone or something doing or being something.', 'In "The loop repeats," the loop is the subject and repeats is the predicate.', 'Good sentences make problem statements easier to solve and code comments easier to follow.', 'What is missing in "Because the value changed"?', 'It is incomplete because the thought is not finished.', 'What does a complete sentence express?', 'A complete thought', 'A list with no relationship'],
  [languageStages.foundations, 'Punctuation Controls Meaning', 'Foundation', 'Punctuation shows stops, joins, emphasis, and relationships between ideas.', 'Punctuation is traffic control for reading.', 'A comma can separate steps: measure, record, compare.', 'Punctuation prevents ambiguity in lab notes, equations explained in words, and instructions.', 'Why does "Let us eat, Kai" differ from "Let us eat Kai"?', 'The comma changes who is being addressed.', 'What does punctuation help control?', 'How ideas are grouped and read', 'The mass of an object'],
  [languageStages.foundations, 'Grammar Basics as Rules for Meaning', 'Foundation', 'Grammar is the system that makes words work together clearly.', 'Grammar is the wiring behind a sentence.', 'Subject-verb agreement makes "the results are" different from "the result is."', 'Clear grammar reduces errors when writing instructions, proofs, and bug reports.', 'Why should subject and verb agree?', 'So the sentence accurately matches one thing or many things.', 'What is grammar for?', 'Making word relationships clear', 'Making writing sound complicated'],
  [languageStages.intermediate, 'Writing Clear Sentences', 'Core', 'A clear sentence puts the main idea where the reader can find it.', 'Clarity means the reader does not have to guess the point.', 'Instead of "Due to it, this changed," write "Gravity changed the ball velocity."', 'Clear sentences are the foundation of clear reasoning and precise code documentation.', 'Which sentence is clearer: "It did it" or "The loop updated the score"?', 'The loop updated the score names the actor and action.', 'What makes a sentence clear?', 'A specific actor, action, and object or idea', 'Extra words that hide the point'],
  [languageStages.intermediate, 'Structuring Paragraphs', 'Core', 'A paragraph develops one main idea with supporting details.', 'A paragraph is a small container for one piece of thinking.', 'Start with a claim, add evidence, then explain why the evidence matters.', 'Proofs, lab reports, and design notes all need organized paragraphs.', 'What should one paragraph usually focus on?', 'One main idea', 'Every topic at once'],
  [languageStages.intermediate, 'Logical Flow', 'Core', 'Logical flow means each sentence follows from the previous one.', 'Flow is a path the reader can walk without jumping gaps.', 'Define the variable, show the equation, then solve it.', 'Algorithms and physics derivations both depend on ordered reasoning.', 'Why define terms before using them?', 'So the reader can follow later steps.', 'What is logical flow?', 'An ordered path from one idea to the next', 'A collection of disconnected facts'],
  [languageStages.intermediate, 'Avoiding Ambiguity', 'Core', 'Ambiguity happens when a sentence can mean more than one thing.', 'An ambiguous sentence is a fork with no sign.', 'The sentence "measure the box with the sensor" could mean the box has the sensor or the sensor does the measuring.', 'Ambiguity causes bugs, bad requirements, and confused science instructions.', 'How can you fix "it changed after it moved"?', 'Name the objects: "Velocity changed after the cart moved down the ramp."', 'What is ambiguity?', 'More than one possible meaning', 'A sentence with too many correct details'],
  [languageStages.intermediate, 'Definitions and Examples', 'Core', 'A strong explanation defines the idea and then gives an example.', 'Definition gives the rule; example makes it visible.', 'Define acceleration as velocity change over time, then show 0 to 10 m/s in 2 s.', 'Teaching AI, math, physics, or code requires both precision and examples.', 'Why pair a definition with an example?', 'The definition is precise and the example makes it concrete.', 'What does a good example do?', 'Shows the idea in a concrete case', 'Replaces the need for accuracy'],
  [languageStages.intermediate, 'Transitions and Signposts', 'Core', 'Transitions show how ideas relate: cause, contrast, sequence, or conclusion.', 'A transition is a road sign for thinking.', 'Words like therefore, however, first, and because tell the reader how to connect ideas.', 'Good transitions make proofs, essays, and technical docs easier to follow.', 'What does "therefore" usually signal?', 'A conclusion from earlier ideas.', 'What is a transition for?', 'Showing the relationship between ideas', 'Adding decoration only'],
  [languageStages.intermediate, 'Evidence and Claims', 'Core', 'A claim says what you think; evidence shows why someone should believe it.', 'A claim is the answer, evidence is the support beam.', 'Claim: the algorithm is slower. Evidence: runtime doubled when input size doubled.', 'Science, debugging, and critical thinking all require evidence-backed claims.', 'Why is "it feels faster" weak evidence?', 'It is subjective and not measured.', 'What should support a claim?', 'Evidence that can be checked', 'A louder voice'],
  [languageStages.advanced, 'Argument Structure', 'Advanced', 'An argument connects premises to a conclusion.', 'An argument is a bridge from reasons to a claim.', 'Premise: all tests passed. Premise: tests cover edge cases. Conclusion: the change is probably safe.', 'Algorithms, proofs, and scientific explanations all use argument structure.', 'What is a premise?', 'A reason used to support a conclusion', 'A random ending sentence'],
  [languageStages.advanced, 'Persuasion with Integrity', 'Advanced', 'Good persuasion helps people see reasons clearly without hiding weaknesses.', 'Persuasion is guiding attention honestly.', 'A fair proposal states benefits, costs, evidence, and uncertainty.', 'Responsible AI and science communication depend on honest persuasion.', 'Why mention uncertainty in a persuasive argument?', 'It builds trust and prevents overclaiming.', 'What is ethical persuasion?', 'Using clear reasons without misleading people', 'Winning by hiding evidence'],
  [languageStages.advanced, 'Clarity of Thought', 'Advanced', 'Clear writing often reveals clear thinking because it forces ideas into testable shape.', 'If you cannot say the idea clearly, you may not fully understand it yet.', 'Rewrite "stuff affects things" as "friction reduces the cart acceleration."', 'Precise thinking improves problem solving in every subject.', 'What should you do when a sentence feels vague?', 'Name the specific actor, action, and result.', 'How does clear writing help thinking?', 'It exposes the exact idea and gaps', 'It hides uncertainty better'],
  [languageStages.advanced, 'Precise Communication', 'Advanced', 'Precise communication chooses words that match the exact relationship.', 'Precision is using the right-sized tool.', 'Say "correlates with" when you do not have evidence for "causes."', 'Precision prevents false claims in data, science, AI, and debate.', 'Why not say "causes" when you only measured correlation?', 'Because correlation alone does not prove cause.', 'What does precision protect?', 'Meaning and truthfulness', 'Longer sentences automatically'],
  [languageStages.advanced, 'Explaining Complex Ideas Simply', 'Advanced', 'A simple explanation keeps the core structure while removing unnecessary load.', 'Simplicity is not dumbing down; it is choosing the right ladder.', 'Explain a neural network as layers of adjustable functions before naming all the math.', 'Great teachers, engineers, and AI tools make complex systems understandable.', 'What should a simple explanation keep?', 'The core relationship that makes the idea work', 'Every technical detail at once'],
  [languageStages.advanced, 'Critical Reading', 'Advanced', 'Critical reading checks claims, evidence, assumptions, and missing alternatives.', 'Read like a scientist: curious, fair, and hard to fool.', 'When a graph claims improvement, inspect axes, sample size, and comparison group.', 'AI outputs, news, documentation, and research papers all require critical reading.', 'What should you inspect before trusting a graph?', 'Axes, labels, scale, data source, and comparison.', 'What is critical reading?', 'Checking claims and evidence carefully', 'Rejecting everything immediately'],
];

function buildSubject(title, specs, subjectKey) {
  return {
    title,
    lessons: specs.map((spec) => lesson(subjectKey, ...spec)),
  };
}

export const deepLessons = {
  math: buildSubject('Math', mathSpecs, 'math'),
  physics: buildSubject('Physics', physicsSpecs, 'physics'),
  cs: buildSubject('Computer Science', csSpecs, 'cs'),
  language: buildSubject('Language & Thinking', languageSpecs, 'language'),
};
