import { Atom, Calculator, Code2 } from 'lucide-react';

export const FOUNDATION_CONCEPTS = [
  {
    id: 'foundation-functions',
    title: 'Functions: Inputs and Outputs',
    labHref: '#labs',
    buildHref: '#build-function-rule-builder',
    microLessons: [
      {
        id: 'foundation-inputs',
        title: 'What is an input?',
        explanation: 'An input is what you put in. It is the starting value.',
        examples: ['Put 3 into a rule.', 'Type your name into a form.', 'Set speed to 20 in a simulator.'],
        representations: {
          numbers: 'Input: 4',
          visual: 'Move a slider. The slider value is the input.',
          code: 'lineOutput(4, 2, 1)',
          realWorld: 'A vending machine input is the button you press.',
        },
        questions: [
          { prompt: 'In lineOutput(3, 2, 1), what is x?', answer: '3', feedback: 'Yes. x is the first input.' },
          { prompt: 'If a slider is set to 7, what is the input?', answer: '7', feedback: 'Yes. The slider value is the input.' },
          { prompt: 'In score(10), what number goes in?', answer: '10', feedback: 'Yes. 10 goes into the rule.' },
        ],
        variations: [
          { prompt: 'In lineOutput(5, 2, 1), what is x?', answer: '5' },
          { prompt: 'If a slider is set to 9, what is the input?', answer: '9' },
        ],
      },
      {
        id: 'foundation-outputs',
        title: 'What is an output?',
        explanation: 'An output is what comes out after the rule runs.',
        examples: ['Input 3 gives output 7.', 'A calculator shows 12.', 'A model predicts 85.'],
        representations: {
          numbers: 'Input 4 -> Output 9',
          visual: 'A point appears on a graph after the input is chosen.',
          code: 'return y',
          realWorld: 'A vending machine output is the snack.',
        },
        questions: [
          { prompt: 'If input 3 gives 7, what is the output?', answer: '7', feedback: 'Yes. 7 came out.' },
          { prompt: 'If a calculator shows 12, what is the output?', answer: '12', feedback: 'Yes. The displayed result is the output.' },
          { prompt: 'If y = 2x and x = 5, what is y?', answer: '10', feedback: 'Yes. 2 times 5 gives 10.' },
        ],
        variations: [
          { prompt: 'If input 4 gives 9, what is the output?', answer: '9' },
          { prompt: 'If y = 3x and x = 2, what is y?', answer: '6' },
        ],
      },
      {
        id: 'foundation-match-input-output',
        title: 'Match inputs to outputs',
        explanation: 'A function pairs each input with an output.',
        examples: ['1 -> 3', '2 -> 5', '3 -> 7', 'Each input has a matching output.'],
        representations: {
          numbers: '2 -> 5',
          visual: 'A table row connects one input to one output.',
          code: 'return 2 * x + 1',
          realWorld: 'A recipe input is cups of flour. The output is dough amount.',
        },
        questions: [
          { prompt: 'In 2 -> 5, what output matches input 2?', answer: '5', feedback: 'Yes. 2 matches with 5.' },
          { prompt: 'In 4 -> 11, what input makes 11?', answer: '4', feedback: 'Yes. 4 is paired with 11.' },
          { prompt: 'If x is 6 and output is 13, what does x equal?', answer: '6', feedback: 'Yes. x is the input.' },
        ],
        variations: [
          { prompt: 'In 3 -> 8, what output matches input 3?', answer: '8' },
          { prompt: 'In 5 -> 12, what input makes 12?', answer: '5' },
        ],
      },
      {
        id: 'foundation-find-rule',
        title: 'Find the rule',
        explanation: 'A rule tells how to turn the input into the output.',
        examples: ['Input 1 -> 3 means maybe double and add 1.', 'Input 2 -> 5 also fits double and add 1.', 'Input 3 -> 7 confirms the pattern.'],
        representations: {
          numbers: 'y = 2x + 1',
          visual: 'A straight line shows the same rule again and again.',
          code: 'const y = 2 * x + 1',
          realWorld: 'A taxi fare can be a starting fee plus dollars per mile.',
        },
        questions: [
          { prompt: 'Rule: double x. If x = 4, what is the output?', answer: '8', feedback: 'Yes. Double 4 is 8.' },
          { prompt: 'Rule: add 3. If x = 5, what is the output?', answer: '8', feedback: 'Yes. 5 plus 3 is 8.' },
          { prompt: 'Rule: 2x + 1. If x = 3, what is y?', answer: '7', feedback: 'Yes. 2 times 3 plus 1 is 7.' },
        ],
        variations: [
          { prompt: 'Rule: double x. If x = 6, what is the output?', answer: '12' },
          { prompt: 'Rule: 2x + 1. If x = 4, what is y?', answer: '9' },
        ],
      },
      {
        id: 'foundation-change-inputs',
        title: 'Change inputs, watch outputs',
        explanation: 'When the input changes, the output may change too.',
        examples: ['If x goes from 2 to 3, y may go from 5 to 7.', 'Changing slope changes outputs faster.', 'Changing intercept shifts outputs up or down.'],
        representations: {
          numbers: 'x = 2 gives 5. x = 3 gives 7.',
          visual: 'The graph point moves when the input changes.',
          code: 'lineOutput(x, m, b)',
          realWorld: 'More study time can change a predicted quiz score.',
        },
        questions: [
          { prompt: 'Rule: y = 2x + 1. If x changes from 2 to 3, does y change?', answer: 'yes', feedback: 'Yes. The output changes from 5 to 7.' },
          { prompt: 'Rule: y = x + 4. If x = 6, what is y?', answer: '10', feedback: 'Yes. 6 plus 4 is 10.' },
          { prompt: 'If the input changes, what should you check next: input or output?', answer: 'output', feedback: 'Yes. Check what came out.' },
        ],
        variations: [
          { prompt: 'Rule: y = x + 4. If x = 8, what is y?', answer: '12' },
          { prompt: 'If x changes, should you expect the output might change?', answer: 'yes' },
        ],
      },
    ],
  },
];

const lessons = {
  math: {
    title: 'Math',
    icon: Calculator,
    color: 'text-cobalt',
    lessons: [
      {
        id: 'math-numbers-variables-equations',
        title: 'Numbers, Variables, and Equations',
        level: 'Foundation',
        bigIdea: 'Numbers measure amounts. Variables name amounts that can change or are not known yet. Equations say two expressions have the same value.',
        whyItMatters: 'Equations turn vague questions into solvable statements, from budgeting to engineering. AI systems also use variables and equations internally when they turn data into predictions.',
        mentalModel: 'Think of a variable as a labeled empty box. An equation is a balance scale: whatever is on the left must match whatever is on the right.',
        guidedExample: 'If x + 4 = 10, the box plus 4 balances with 10. Subtract 4 from both sides and x = 6.',
        bridge: 'Physics uses variables like time, mass, and speed. Computer science uses variables to store values while a program runs.',
        prediction: {
          question: 'If y - 3 = 9, what value do you predict y must have?',
          answer: 'y must be 12 because 12 - 3 = 9.',
        },
        quiz: {
          question: 'What does a variable usually represent?',
          options: ['A value that can change or is unknown', 'Only the number zero', 'A drawing tool for graphs', 'A force acting on an object'],
          correctIndex: 0,
          feedback: [
            'Correct. A variable is a name for a value you can use in reasoning.',
            'No. A variable can equal zero, but it can represent many values.',
            'Not quite. Variables can be graphed, but they are not drawing tools.',
            'No. Force is a physics quantity that can be stored in a variable.',
          ],
        },
      },
      {
        id: 'math-algebra-solving-unknowns',
        title: 'Algebra and Solving Unknowns',
        level: 'Foundation',
        bigIdea: 'Algebra is the art of rearranging relationships so the unknown value becomes clear.',
        whyItMatters: 'Solving unknowns helps you compare plans, predict outcomes, and reverse-engineer missing information. AI training often solves for values that make predictions fit data better.',
        mentalModel: 'Solving an equation is like carefully untangling a knot. You undo operations in reverse order while keeping both sides balanced.',
        guidedExample: 'For 3x + 2 = 14, subtract 2 to get 3x = 12. Divide by 3 to get x = 4.',
        bridge: 'Algebra powers physics formulas such as F = ma and computer programs that calculate missing values from known inputs.',
        prediction: {
          question: 'If 2x + 5 = 17, what operation should you do first?',
          answer: 'Subtract 5 from both sides first, giving 2x = 12.',
        },
        quiz: {
          question: 'Why do we do the same operation to both sides of an equation?',
          options: ['To keep the equation balanced', 'To make numbers larger', 'To change the meaning of the unknown', 'To avoid using variables'],
          correctIndex: 0,
          feedback: [
            'Correct. Equal changes preserve equality.',
            'No. Sometimes numbers get smaller; balance is the goal.',
            'No. The unknown keeps its meaning while we reveal its value.',
            'No. Algebra depends on variables.',
          ],
        },
      },
      {
        id: 'math-functions-graphs',
        title: 'Functions and Graphs',
        level: 'Foundation',
        bigIdea: 'A function connects each input to an output. A graph shows that relationship as a picture.',
        whyItMatters: 'Graphs make patterns visible in prices, motion, climate, code performance, and AI predictions. Seeing the shape helps you understand behavior quickly.',
        mentalModel: 'A function is a machine; a graph is its trail. Every point on the graph says, "this input produced this output."',
        guidedExample: 'For f(x) = 2x + 1, input 0 gives 1, input 1 gives 3, and input 2 gives 5. Plotting those points creates a straight line.',
        bridge: 'Physics graphs position over time, and CS functions turn inputs into outputs just like math functions do.',
        prediction: {
          question: 'If f(x) = x + 5, what do you predict happens to the graph when x increases by 1?',
          answer: 'The output also increases by 1, so the graph rises steadily.',
        },
        quiz: {
          question: 'What does one point on a function graph show?',
          options: ['One input-output pair', 'Only the largest output', 'The unit of measurement', 'The computer memory address'],
          correctIndex: 0,
          feedback: [
            'Correct. A point like (2, 5) means input 2 gives output 5.',
            'No. A graph contains many points, not only the largest one.',
            'No. Units help interpret graphs but are not the point itself.',
            'No. Memory addresses are a computer science detail.',
          ],
        },
      },
      {
        id: 'math-slope-rate-change',
        title: 'Slope and Rate of Change',
        level: 'Core',
        bigIdea: 'Slope measures how much the output changes when the input changes by one step.',
        whyItMatters: 'Slope describes speed, growth, cost per item, and trends in data. In AI, rates of change guide how a model adjusts during training.',
        mentalModel: 'Slope is the steepness of a ramp. A larger positive slope climbs faster; a negative slope goes downward as you move right.',
        guidedExample: 'If a line goes from (1, 3) to (4, 9), slope = (9 - 3) / (4 - 1) = 2. The output rises 2 for each 1 step in input.',
        bridge: 'In physics, velocity is the slope of a position-time graph. In CS, performance graphs show how runtime changes as input grows.',
        prediction: {
          question: 'If a line has slope -3, what happens to y when x increases by 1?',
          answer: 'y decreases by 3.',
        },
        quiz: {
          question: 'Which phrase best describes slope?',
          options: ['Change in output divided by change in input', 'The starting point of every graph', 'The total area under a curve', 'A list of program instructions'],
          correctIndex: 0,
          feedback: [
            'Correct. Slope is rise over run.',
            'No. The starting point may be an intercept, not slope.',
            'No. Area under a curve connects to integrals.',
            'No. Instructions belong to programming.',
          ],
        },
      },
      {
        id: 'math-systems-equations',
        title: 'Systems of Equations',
        level: 'Core',
        bigIdea: 'A system of equations is a set of relationships that must all be true at the same time.',
        whyItMatters: 'Systems help solve mixtures, schedules, budgets, and engineering constraints. AI and graphics often solve many equations together to fit models or render scenes.',
        mentalModel: 'Each equation is a rule. The solution is the place where all the rules agree.',
        guidedExample: 'If x + y = 10 and x = 6, then y must be 4. Both equations are true at the same time.',
        bridge: 'Physics uses systems to model connected forces. Computer science uses systems when multiple constraints must be satisfied together.',
        prediction: {
          question: 'If two lines cross once, how many solutions do you predict their system has?',
          answer: 'One solution, located at the crossing point.',
        },
        quiz: {
          question: 'What is a solution to a system of equations?',
          options: ['Values that make every equation true', 'Any number on the page', 'Only the largest variable', 'A graph with no labels'],
          correctIndex: 0,
          feedback: [
            'Correct. A system solution must satisfy all equations.',
            'No. Random numbers usually do not satisfy every relationship.',
            'No. The solution can include several variables.',
            'No. A graph can show a system, but labels do not define the solution.',
          ],
        },
      },
      {
        id: 'math-exponents-logarithms',
        title: 'Exponents and Logarithms',
        level: 'Core',
        bigIdea: 'Exponents describe repeated multiplication. Logarithms reverse exponents by asking what power was used.',
        whyItMatters: 'Exponential growth appears in populations, interest, sound, data storage, and algorithms. Logarithms help compress huge ranges into understandable scales.',
        mentalModel: 'An exponent is a growth engine. A logarithm is the detective that asks, "how many times did we multiply?"',
        guidedExample: '2 to the 3rd power is 8. So log base 2 of 8 is 3 because 2 had to be multiplied by itself 3 times to reach 8.',
        bridge: 'Waves use logarithmic decibels, and CS uses logarithms to describe efficient search in sorted data.',
        prediction: {
          question: 'If 10 to the 4th power is 10,000, what is log base 10 of 10,000?',
          answer: 'It is 4 because 10 uses power 4 to make 10,000.',
        },
        quiz: {
          question: 'What does a logarithm undo?',
          options: ['An exponent', 'A unit conversion', 'A force', 'A loop condition'],
          correctIndex: 0,
          feedback: [
            'Correct. Logs and exponents are inverse ideas.',
            'No. Unit conversions are separate measurement tools.',
            'No. Force is a physical interaction.',
            'No. Loop conditions are programming logic.',
          ],
        },
      },
      {
        id: 'math-trigonometry-basics',
        title: 'Trigonometry Basics',
        level: 'Core',
        bigIdea: 'Trigonometry connects angles with side lengths and circular motion.',
        whyItMatters: 'Trig helps with navigation, architecture, waves, games, robotics, and projectile motion. AI systems for vision and robotics often use geometry and angles.',
        mentalModel: 'Sine and cosine are shadow-makers. As a point moves around a circle, cosine gives its horizontal shadow and sine gives its vertical shadow.',
        guidedExample: 'In a right triangle, sine of an angle equals opposite side divided by hypotenuse. If opposite is 3 and hypotenuse is 5, sin(angle) = 3/5 = 0.6.',
        bridge: 'Physics uses trig to split motion into horizontal and vertical parts. Computer graphics uses trig to rotate objects.',
        prediction: {
          question: 'If a projectile launches at a steeper angle, what happens to its vertical component?',
          answer: 'The vertical component increases because more of the speed points upward.',
        },
        quiz: {
          question: 'What does sine relate in a right triangle?',
          options: ['Opposite side divided by hypotenuse', 'Mass times acceleration', 'Input size squared', 'The number of variables'],
          correctIndex: 0,
          feedback: [
            'Correct. Sine connects an angle to opposite over hypotenuse.',
            'No. Mass times acceleration is force.',
            'No. Input size squared is an algorithm growth pattern.',
            'No. Variables are algebra symbols.',
          ],
        },
      },
      {
        id: 'math-calculus-derivatives',
        title: 'Calculus: Derivatives',
        level: 'Advanced',
        bigIdea: 'A derivative measures the instant rate of change of a function.',
        whyItMatters: 'Derivatives describe velocity, growth, optimization, and sensitivity. Machine learning uses derivatives to reduce loss during training.',
        mentalModel: 'Zoom in on a smooth curve until it looks almost straight. The slope of that tiny straight piece is the derivative at that point.',
        guidedExample: 'If s(t) = t squared, then its derivative is 2t. At t = 4, the rate of change is 8 units per second.',
        bridge: 'Physics uses derivatives for velocity and acceleration. AI uses them to decide how to update model weights.',
        prediction: {
          question: 'If a position graph is flat at one moment, what do you predict the velocity is at that moment?',
          answer: 'The velocity is zero because the position is not changing at that instant.',
        },
        quiz: {
          question: 'What does the derivative of position with respect to time give?',
          options: ['Velocity', 'Mass', 'Probability', 'Memory usage'],
          correctIndex: 0,
          feedback: [
            'Correct. Velocity is the rate of change of position.',
            'No. Mass is not a rate of change.',
            'No. Probability measures uncertainty.',
            'No. Memory usage is a computing resource.',
          ],
        },
      },
      {
        id: 'math-probability-expected-value',
        title: 'Probability and Expected Value',
        level: 'Core',
        bigIdea: 'Probability measures uncertainty. Expected value is the long-run average outcome if a situation repeats many times.',
        whyItMatters: 'Expected value guides choices in games, insurance, medicine, forecasting, and AI decision systems. It helps compare uncertain options rationally.',
        mentalModel: 'Expected value is the average you would expect after many repeats, not a promise for the next single try.',
        guidedExample: 'If a game pays 10 dollars with probability 0.2 and 0 dollars otherwise, expected value is 10 x 0.2 + 0 x 0.8 = 2 dollars.',
        bridge: 'Physics uses probability in measurement uncertainty. AI uses probabilities and expected outcomes when choosing among possible actions.',
        prediction: {
          question: 'If a 1 dollar prize has a 50 percent chance, what is its expected value?',
          answer: 'The expected value is 50 cents because 1 x 0.5 = 0.5.',
        },
        quiz: {
          question: 'What is expected value?',
          options: ['The probability-weighted average outcome', 'The biggest possible outcome only', 'A guarantee for the next trial', 'The slope of a line'],
          correctIndex: 0,
          feedback: [
            'Correct. Expected value combines outcomes with their probabilities.',
            'No. It accounts for all outcomes, not only the biggest one.',
            'No. It describes long-run average behavior.',
            'No. Slope measures rate of change.',
          ],
        },
      },
      {
        id: 'math-linear-algebra-vectors-matrices',
        title: 'Linear Algebra: Vectors and Matrices',
        level: 'Advanced',
        bigIdea: 'Vectors store quantities with direction or multiple components. Matrices organize numbers that can transform vectors or represent relationships.',
        whyItMatters: 'Linear algebra powers 3D graphics, physics simulations, data science, and modern AI. Neural networks are built from many matrix operations.',
        mentalModel: 'A vector is an arrow or a row of features. A matrix is a machine that can stretch, rotate, mix, or project those features.',
        guidedExample: 'The vector [3, 4] can represent moving 3 units right and 4 units up. Its length is 5 by the Pythagorean theorem.',
        bridge: 'Physics uses vectors for forces and velocity. Computer science uses matrices to process images, graphs, and AI model weights.',
        prediction: {
          question: 'If a force has components [0, 10], which direction do you predict it points?',
          answer: 'It points straight upward because the horizontal component is 0 and the vertical component is positive.',
        },
        quiz: {
          question: 'Why are vectors useful?',
          options: ['They can store direction and multiple components', 'They only store true or false', 'They erase uncertainty', 'They prevent loops in code'],
          correctIndex: 0,
          feedback: [
            'Correct. Vectors are compact ways to represent multi-part quantities.',
            'No. Booleans store true or false.',
            'No. Probability handles uncertainty.',
            'No. Loop control is a programming issue.',
          ],
        },
      },
    ],
  },
  physics: {
    title: 'Physics',
    icon: Atom,
    color: 'text-fern',
    lessons: [
      {
        id: 'physics-measurement-units-estimation',
        title: 'Measurement, Units, and Estimation',
        level: 'Foundation',
        bigIdea: 'Physics begins by measuring the world with units and making reasonable estimates when exact values are unavailable.',
        whyItMatters: 'Good measurement prevents bad designs, unsafe machines, and misleading data. AI systems also depend on clean units and sensible input scales.',
        mentalModel: 'A number without a unit is like an address without a street name. The unit tells what kind of quantity the number describes.',
        guidedExample: 'A desk might be about 1.2 meters long. Saying "1.2" alone is incomplete; saying "1.2 meters" makes the measurement meaningful.',
        bridge: 'Math handles unit conversions, and CS programs must track units carefully to avoid silent calculation errors.',
        prediction: {
          question: 'Which is more reasonable for the height of a door: 2 meters or 20 meters?',
          answer: '2 meters is reasonable. 20 meters would be taller than a many-story building.',
        },
        quiz: {
          question: 'Why are units important?',
          options: ['They tell what a number measures', 'They make every number larger', 'They replace equations', 'They are only needed in chemistry'],
          correctIndex: 0,
          feedback: [
            'Correct. Units give physical meaning to numbers.',
            'No. Units do not make values larger or smaller by themselves.',
            'No. Equations still matter.',
            'No. Units are essential throughout science and engineering.',
          ],
        },
      },
      {
        id: 'physics-motion-position-velocity-acceleration',
        title: 'Motion: Position, Velocity, Acceleration',
        level: 'Foundation',
        bigIdea: 'Motion describes how position changes over time. Velocity is change in position, and acceleration is change in velocity.',
        whyItMatters: 'Motion matters for driving, sports, robotics, rockets, and animation. AI systems that navigate the world must predict motion to act safely.',
        mentalModel: 'Position is where you are, velocity is how fast your position changes, and acceleration is how fast your velocity changes.',
        guidedExample: 'If a runner moves from 10 meters to 18 meters between 2 and 4 seconds, average velocity is (18 - 10) / (4 - 2) = 4 meters per second.',
        bridge: 'Calculus links these ideas mathematically, and CS simulations update position and velocity step by step.',
        prediction: {
          question: 'If velocity stays constant, what do you predict acceleration is?',
          answer: 'Acceleration is zero because velocity is not changing.',
        },
        quiz: {
          question: 'Which quantity measures change in velocity?',
          options: ['Acceleration', 'Position', 'Mass', 'Voltage'],
          correctIndex: 0,
          feedback: [
            'Correct. Acceleration is the rate of change of velocity.',
            'No. Position tells location.',
            'No. Mass describes inertia.',
            'No. Voltage belongs to electricity.',
          ],
        },
      },
      {
        id: 'physics-graphing-motion',
        title: 'Graphing Motion',
        level: 'Core',
        bigIdea: 'Motion graphs show how position, velocity, or acceleration changes over time.',
        whyItMatters: 'Graphs reveal patterns that raw numbers hide. Robots, vehicles, and AI trackers use motion data to predict what happens next.',
        mentalModel: 'A motion graph is a story told with axes: time usually moves right, and the vertical value shows what is changing.',
        guidedExample: 'On a position-time graph, a steeper line means faster motion. A flat line means the object is not changing position.',
        bridge: 'Slope from math becomes velocity in physics, and CS uses plotted sensor data to debug moving systems.',
        prediction: {
          question: 'If a position-time graph curves upward and gets steeper, what happens to speed?',
          answer: 'Speed increases because the slope of the position graph is increasing.',
        },
        quiz: {
          question: 'What does slope on a position-time graph represent?',
          options: ['Velocity', 'Mass', 'Energy stored in a battery', 'A loop count'],
          correctIndex: 0,
          feedback: [
            'Correct. The slope of position over time is velocity.',
            'No. Mass is not read from graph slope here.',
            'No. Battery energy is a different quantity.',
            'No. Loop count is a programming idea.',
          ],
        },
      },
      {
        id: 'physics-forces-newtons-laws',
        title: "Forces and Newton's Laws",
        level: 'Core',
        bigIdea: 'Forces are pushes or pulls. Newtons laws explain how forces change motion and why objects resist changes to their motion.',
        whyItMatters: 'Forces shape bridges, vehicles, sports, machines, and robots. AI-controlled robots still have to obey physical laws when they move.',
        mentalModel: 'An object keeps doing what it is doing unless a net force changes its motion. More mass means more resistance to change.',
        guidedExample: 'If a 2 kg object accelerates at 3 meters per second squared, net force is F = ma = 6 newtons.',
        bridge: 'Algebra rearranges F = ma, and CS simulations use the law to update virtual objects realistically.',
        prediction: {
          question: 'If net force is zero, what do you predict happens to an objects velocity?',
          answer: 'Its velocity stays constant. It may be still, or it may keep moving at the same speed and direction.',
        },
        quiz: {
          question: 'What does F = ma connect?',
          options: ['Force, mass, and acceleration', 'Voltage, current, and resistance', 'Probability and expected value', 'Arrays and objects'],
          correctIndex: 0,
          feedback: [
            'Correct. Net force equals mass times acceleration.',
            'No. Voltage, current, and resistance are linked by Ohms law.',
            'No. That is a probability idea.',
            'No. Those are computer science structures.',
          ],
        },
      },
      {
        id: 'physics-friction-constraints',
        title: 'Friction and Constraints',
        level: 'Core',
        bigIdea: 'Friction resists sliding motion, and constraints limit how objects are allowed to move.',
        whyItMatters: 'Friction makes walking, braking, gripping, and machines possible, but it also wastes energy as heat. Robots need friction and constraints to interact with the world.',
        mentalModel: 'Friction is the surface saying "not so fast." A constraint is a rule like "stay on this track" or "move only along this rope."',
        guidedExample: 'A box on a rough floor needs a push large enough to overcome static friction before it starts sliding.',
        bridge: 'Inequalities in math can describe limits, and game engines use constraints to keep simulated objects believable.',
        prediction: {
          question: 'If a floor becomes smoother, what do you predict happens to the friction force?',
          answer: 'The friction force usually decreases, so objects slide more easily.',
        },
        quiz: {
          question: 'What does friction usually do?',
          options: ['Opposes relative sliding motion', 'Creates energy from nothing', 'Removes the need for mass', 'Sorts data faster'],
          correctIndex: 0,
          feedback: [
            'Correct. Friction acts against sliding or attempted sliding.',
            'No. Friction transforms mechanical energy into heat; it does not create energy.',
            'No. Mass still matters.',
            'No. Sorting is an algorithms topic.',
          ],
        },
      },
      {
        id: 'physics-work-energy',
        title: 'Work and Energy',
        level: 'Core',
        bigIdea: 'Work transfers energy when a force moves something over a distance. Energy is the capacity to cause change.',
        whyItMatters: 'Work and energy explain engines, batteries, muscles, roller coasters, and power use. AI can optimize energy systems, but conservation rules still apply.',
        mentalModel: 'Energy is a budget for change. Work is one way to move that budget from one place or form to another.',
        guidedExample: 'If you push with 10 newtons over 3 meters in the direction of motion, you do 30 joules of work.',
        bridge: 'Algebra calculates work, physics explains energy transfer, and CS models energy in simulations and optimization tools.',
        prediction: {
          question: 'If you push hard on a wall but it does not move, how much mechanical work do you predict you do on the wall?',
          answer: 'Zero mechanical work, because work needs displacement in the direction of force.',
        },
        quiz: {
          question: 'What must happen for a force to do mechanical work?',
          options: ['The object must move through a distance', 'The object must be blue', 'The force must be random', 'The code must use a loop'],
          correctIndex: 0,
          feedback: [
            'Correct. Work involves force through displacement.',
            'No. Color is irrelevant.',
            'No. The force does not need to be random.',
            'No. Loops are not required for physical work.',
          ],
        },
      },
      {
        id: 'physics-momentum',
        title: 'Momentum',
        level: 'Core',
        bigIdea: 'Momentum measures motion using mass and velocity. It is conserved in many collision situations.',
        whyItMatters: 'Momentum explains crashes, sports impacts, rockets, and recoil. Robots and simulations need momentum to predict collisions realistically.',
        mentalModel: 'Momentum is how hard it is to stop something that is moving. Heavy and fast objects have more momentum.',
        guidedExample: 'A 4 kg cart moving at 3 meters per second has momentum p = mv = 12 kg meters per second.',
        bridge: 'Vectors from math describe momentum direction, and CS collision engines use conservation rules to update motion.',
        prediction: {
          question: 'Which has more momentum: a slow bicycle or a fast truck?',
          answer: 'The fast truck usually has much more momentum because both mass and velocity are large.',
        },
        quiz: {
          question: 'What is the formula for momentum?',
          options: ['p = mv', 'F = qE', 'V = IR', 'n squared'],
          correctIndex: 0,
          feedback: [
            'Correct. Momentum equals mass times velocity.',
            'No. That formula belongs to electric force.',
            'No. V = IR is Ohms law.',
            'No. n squared describes algorithm growth.',
          ],
        },
      },
      {
        id: 'physics-waves-frequency',
        title: 'Waves and Frequency',
        level: 'Core',
        bigIdea: 'A wave carries energy through a pattern that repeats. Frequency tells how many cycles happen each second.',
        whyItMatters: 'Sound, light, radio, earthquakes, and medical imaging all involve waves. AI systems process wave-like signals in audio, speech, and sensors.',
        mentalModel: 'A wave is a repeated wiggle moving through space or a medium. Frequency is how quickly the wiggle repeats.',
        guidedExample: 'A sound wave at 440 hertz vibrates 440 times per second. That frequency is heard as the musical note A above middle C.',
        bridge: 'Trigonometry describes waves with sine and cosine, and CS stores sound waves as sampled data.',
        prediction: {
          question: 'If frequency increases, what do you predict happens to the pitch of a sound?',
          answer: 'The pitch gets higher.',
        },
        quiz: {
          question: 'What does frequency measure?',
          options: ['Cycles per second', 'Mass per meter', 'The slope of a line only', 'The number of objects in an array'],
          correctIndex: 0,
          feedback: [
            'Correct. Frequency is measured in hertz, or cycles per second.',
            'No. That would be a kind of density.',
            'No. Slope is a math rate, not frequency by itself.',
            'No. Array length is a CS idea.',
          ],
        },
      },
      {
        id: 'physics-electricity-vir',
        title: 'Electricity: Voltage, Current, Resistance',
        level: 'Core',
        bigIdea: 'Voltage pushes electric charge, current is the flow of charge, and resistance opposes that flow.',
        whyItMatters: 'Electricity powers computers, homes, sensors, and robots. AI hardware depends on carefully controlled electrical circuits.',
        mentalModel: 'Think of a circuit like water pipes: voltage is pressure, current is flow, and resistance is a narrow section that limits flow.',
        guidedExample: 'Ohms law says V = IR. If current is 2 amps through 5 ohms, voltage is 10 volts.',
        bridge: 'Algebra solves circuit relationships, and computer hardware uses electrical states to represent information.',
        prediction: {
          question: 'If voltage stays the same and resistance increases, what happens to current?',
          answer: 'Current decreases because I = V / R.',
        },
        quiz: {
          question: 'What does resistance do in a circuit?',
          options: ['Opposes current', 'Stores source code', 'Measures uncertainty', 'Makes gravity stronger'],
          correctIndex: 0,
          feedback: [
            'Correct. Resistance limits current flow.',
            'No. Source code is stored in digital memory.',
            'No. Probability measures uncertainty.',
            'No. Gravity is separate from electrical resistance.',
          ],
        },
      },
      {
        id: 'physics-circuits-computation',
        title: 'Circuits and Computation',
        level: 'Advanced',
        bigIdea: 'Circuits can control electrical signals, and carefully arranged signals can represent logic and computation.',
        whyItMatters: 'Every computer, phone, and AI accelerator is built from circuits that manipulate bits. Computation is physical, not just abstract.',
        mentalModel: 'A circuit is a decision path for electricity. Logic gates are tiny decision makers that turn input signals into output signals.',
        guidedExample: 'An AND gate outputs 1 only when both inputs are 1. If either input is 0, the output is 0.',
        bridge: 'Boolean algebra from math describes logic gates, and CS builds programs on top of layers of circuit behavior.',
        prediction: {
          question: 'What do you predict an AND gate outputs when inputs are 1 and 0?',
          answer: 'It outputs 0 because both inputs are not 1.',
        },
        quiz: {
          question: 'Why do circuits matter for computer science?',
          options: ['They physically implement logic and memory', 'They remove the need for algorithms', 'They make all programs correct', 'They only measure projectile motion'],
          correctIndex: 0,
          feedback: [
            'Correct. Computation is built from physical circuits.',
            'No. Algorithms still define what computation should do.',
            'No. Circuits do not guarantee program correctness.',
            'No. Circuits can measure motion, but their role is much broader.',
          ],
        },
      },
    ],
  },
  cs: {
    title: 'Computer Science',
    icon: Code2,
    color: 'text-ember',
    lessons: [
      {
        id: 'cs-how-computers-think',
        title: 'How Computers Think',
        level: 'Foundation',
        bigIdea: 'Computers follow exact instructions using simple operations on stored information.',
        whyItMatters: 'Understanding this helps you write clearer programs and judge AI tools more realistically. Computers are fast and literal, not naturally wise.',
        mentalModel: 'A computer is an extremely fast rule follower. It does not guess your intent unless a program or model has been built to handle that uncertainty.',
        guidedExample: 'If you tell a computer to add 2 and 3, it follows the instruction exactly. If you give unclear instructions, it cannot automatically know what you meant.',
        bridge: 'Math gives exact rules, and physics provides the circuits that make those rules run on real hardware.',
        prediction: {
          question: 'If instructions are ambiguous, what do you predict a normal program does?',
          answer: 'It follows the written instructions, fails, or produces unintended behavior. It does not magically infer the right goal.',
        },
        quiz: {
          question: 'What is a computer especially good at?',
          options: ['Following precise instructions quickly', 'Understanding vague intent perfectly', 'Ignoring data', 'Breaking physics laws'],
          correctIndex: 0,
          feedback: [
            'Correct. Speed and precision are core strengths.',
            'No. Vague intent requires careful design or AI support.',
            'No. Computers process data.',
            'No. Computers are physical systems.',
          ],
        },
      },
      {
        id: 'cs-variables-data-types',
        title: 'Variables and Data Types',
        level: 'Foundation',
        bigIdea: 'Variables store values, and data types describe what kind of value is stored.',
        whyItMatters: 'Correct data types prevent bugs and make programs easier to reason about. AI pipelines also need well-structured data to learn from examples.',
        mentalModel: 'A variable is a labeled container. The data type tells whether the container holds a number, text, true/false value, list, or object.',
        guidedExample: 'age = 16 stores a number, while name = "Maya" stores text. You can do arithmetic with age but not with name in the same way.',
        bridge: 'Math variables represent quantities, while CS variables store values in memory while a program runs.',
        prediction: {
          question: 'What problem might happen if a program treats the text "5" like the number 5?',
          answer: 'It may concatenate text instead of doing arithmetic, or it may throw a type error.',
        },
        quiz: {
          question: 'What does a data type describe?',
          options: ['The kind of value stored', 'The color of the screen', 'The force on an object', 'The height of a graph'],
          correctIndex: 0,
          feedback: [
            'Correct. Types describe categories like number, string, boolean, and object.',
            'No. Screen color is a display property.',
            'No. Force is physics.',
            'No. Graph height is visual, not a data type.',
          ],
        },
      },
      {
        id: 'cs-conditionals',
        title: 'Conditionals',
        level: 'Foundation',
        bigIdea: 'Conditionals let programs choose different actions based on whether a statement is true or false.',
        whyItMatters: 'Conditionals power logins, games, recommendations, safety checks, and interactive apps. AI systems often sit inside larger programs that still use clear rules.',
        mentalModel: 'A conditional is a fork in the road: if this is true, go one way; otherwise, go another way.',
        guidedExample: 'If temperature < 32, show "freezing warning." Otherwise, show "above freezing." The program responds to the value.',
        bridge: 'Inequalities from math become decisions in code, and physics simulations use conditionals for collisions and limits.',
        prediction: {
          question: 'If score is 85 and the rule is score >= 90, does the condition pass?',
          answer: 'No. 85 is less than 90, so the condition is false.',
        },
        quiz: {
          question: 'What does an if statement do?',
          options: ['Runs code based on a condition', 'Repeats forever by itself', 'Stores every file on a computer', 'Measures voltage'],
          correctIndex: 0,
          feedback: [
            'Correct. If statements control which branch runs.',
            'No. Repetition is handled by loops.',
            'No. File storage is separate.',
            'No. Voltage is a physics/electronics quantity.',
          ],
        },
      },
      {
        id: 'cs-loops',
        title: 'Loops',
        level: 'Foundation',
        bigIdea: 'Loops repeat instructions while a condition is true or for a set number of steps.',
        whyItMatters: 'Loops process lists, animate motion, run simulations, and train AI over many examples. Without loops, programs would be painfully repetitive.',
        mentalModel: 'A loop is a controlled repeat button. The key word is controlled: it needs a stopping rule.',
        guidedExample: 'A loop can print numbers 1 through 5 by increasing a counter each time and stopping after 5.',
        bridge: 'Physics simulations loop through time steps, and math sequences use repeated patterns.',
        prediction: {
          question: 'If a loop condition never becomes false, what happens?',
          answer: 'The loop keeps running, causing an infinite loop unless something stops the program.',
        },
        quiz: {
          question: 'Why are loops useful?',
          options: ['They repeat work without rewriting the same code', 'They make all code run instantly', 'They replace variables', 'They remove uncertainty from probability'],
          correctIndex: 0,
          feedback: [
            'Correct. Loops make repeated work concise and consistent.',
            'No. Loops still take time to run.',
            'No. Loops often depend on variables.',
            'No. Probability still handles uncertainty.',
          ],
        },
      },
      {
        id: 'cs-functions',
        title: 'Functions',
        level: 'Foundation',
        bigIdea: 'A function is a reusable block of code that can take inputs, perform work, and return an output.',
        whyItMatters: 'Functions make programs organized, testable, and easier to change. AI models can also be viewed as functions from input data to predictions.',
        mentalModel: 'A function is a named mini-machine. You feed it inputs, it follows its instructions, and it gives back a result.',
        guidedExample: 'double(x) returns x * 2. double(7) returns 14.',
        bridge: 'Math functions and code functions share the input-output idea, and physics formulas can be packaged as functions in simulations.',
        prediction: {
          question: 'If square(x) returns x * x, what does square(6) return?',
          answer: 'It returns 36.',
        },
        quiz: {
          question: 'What is a major benefit of functions?',
          options: ['Reusing logic without rewriting it', 'Making variables impossible', 'Preventing all bugs automatically', 'Changing gravity'],
          correctIndex: 0,
          feedback: [
            'Correct. Functions package reusable logic.',
            'No. Functions often use variables.',
            'No. Functions help testing, but bugs can still happen.',
            'No. Gravity is not changed by code functions.',
          ],
        },
      },
      {
        id: 'cs-arrays-objects',
        title: 'Arrays and Objects',
        level: 'Core',
        bigIdea: 'Arrays store ordered collections, while objects store named pieces of information.',
        whyItMatters: 'Most real programs handle groups of data, not single values. AI datasets, game entities, users, and lab measurements all need structure.',
        mentalModel: 'An array is like a numbered shelf. An object is like an index card with labeled fields.',
        guidedExample: 'scores = [80, 92, 75] is an array. student = { name: "Ari", score: 92 } is an object.',
        bridge: 'Vectors in math resemble arrays of numbers, and physics objects can store mass, position, and velocity as fields.',
        prediction: {
          question: 'If you need to store a students name and grade together, would an object or a single number fit better?',
          answer: 'An object fits better because it can label multiple related values.',
        },
        quiz: {
          question: 'What is an array best for?',
          options: ['An ordered collection of values', 'Only one true/false value', 'A force diagram', 'A logarithm rule'],
          correctIndex: 0,
          feedback: [
            'Correct. Arrays store multiple values in order.',
            'No. A boolean stores true or false.',
            'No. Force diagrams are physics representations.',
            'No. Logarithms are math functions.',
          ],
        },
      },
      {
        id: 'cs-data-structures',
        title: 'Data Structures',
        level: 'Core',
        bigIdea: 'A data structure organizes information so a program can use it efficiently.',
        whyItMatters: 'Search engines, maps, databases, games, and AI systems rely on the right structures. Good organization can change a slow idea into a practical tool.',
        mentalModel: 'Choosing a data structure is choosing a container: a stack is a pile, a queue is a line, a tree branches, and a graph connects nodes.',
        guidedExample: 'A browser back button behaves like a stack: the last page you visited is the first one you return to.',
        bridge: 'Graphs connect to math networks and physics systems, while AI uses tensors, trees, and graphs to represent data.',
        prediction: {
          question: 'Which structure fits a waiting line: stack or queue?',
          answer: 'A queue fits because the first person in line is served first.',
        },
        quiz: {
          question: 'Which structure is best for representing connected cities and roads?',
          options: ['Graph', 'Single boolean', 'Plain number', 'One character'],
          correctIndex: 0,
          feedback: [
            'Correct. Graphs represent nodes and connections.',
            'No. A boolean is too small for a network.',
            'No. One number cannot represent all relationships.',
            'No. One character cannot hold a road network.',
          ],
        },
      },
      {
        id: 'cs-algorithms-big-o',
        title: 'Algorithms and Big-O',
        level: 'Core',
        bigIdea: 'An algorithm is a step-by-step method. Big-O describes how its work grows as input size increases.',
        whyItMatters: 'Scaling determines whether software stays fast with real data. AI, search, maps, and apps all depend on algorithms that grow reasonably.',
        mentalModel: 'Big-O is a growth warning label. It tells you whether extra input causes a small, medium, or explosive increase in work.',
        guidedExample: 'Checking every pair in a list of n items is often O(n squared). If n doubles, the work can become about four times larger.',
        bridge: 'Math describes growth rates, and the complexity lab lets you see how O(log n), O(n), and O(n squared) separate as n increases.',
        prediction: {
          question: 'As n gets very large, which grows faster: n or n squared?',
          answer: 'n squared grows much faster.',
        },
        quiz: {
          question: 'What does Big-O describe?',
          options: ['How work grows with input size', 'The exact brand of computer', 'The voltage in a wire', 'The answer to every bug'],
          correctIndex: 0,
          feedback: [
            'Correct. Big-O focuses on growth as inputs scale.',
            'No. Hardware affects speed but not the algorithmic growth label.',
            'No. Voltage is an electrical quantity.',
            'No. Debugging still requires investigation.',
          ],
        },
      },
      {
        id: 'cs-debugging-testing',
        title: 'Debugging and Testing',
        level: 'Core',
        bigIdea: 'Debugging finds why code behaves incorrectly. Testing checks whether code behaves as expected.',
        whyItMatters: 'Reliable software needs evidence, not hope. Tests protect apps, robots, financial systems, and AI pipelines from silent mistakes.',
        mentalModel: 'Debugging is detective work. Testing is building checkpoints so the same mistake is easier to catch next time.',
        guidedExample: 'If a function should return 10 but returns 9, a test can expose the mismatch. Debugging then traces the inputs and steps to find the cause.',
        bridge: 'Science experiments compare predictions to observations; software tests compare expected output to actual output.',
        prediction: {
          question: 'If a bug appears only for negative numbers, what kind of test should you add?',
          answer: 'Add a test with negative inputs so the case is checked automatically in the future.',
        },
        quiz: {
          question: 'What is the main purpose of a test?',
          options: ['Check whether code meets an expected behavior', 'Make code visually colorful', 'Replace all human thinking', 'Measure projectile height'],
          correctIndex: 0,
          feedback: [
            'Correct. Tests compare actual behavior with expected behavior.',
            'No. Visual style is separate.',
            'No. Tests support thinking; they do not replace it.',
            'No. Projectile height belongs to a physics simulation.',
          ],
        },
      },
      {
        id: 'cs-ai-basics-models-loss-training',
        title: 'AI Basics: Models, Loss, Training',
        level: 'Advanced',
        bigIdea: 'An AI model learns a function from examples. Loss measures error, and training adjusts the model to reduce that error.',
        whyItMatters: 'AI supports search, translation, tutoring, medical imaging, robotics, and science. Understanding training helps you use AI critically instead of treating it as magic.',
        mentalModel: 'A model is a prediction machine with adjustable knobs. Loss tells how wrong it was. Training turns the knobs to make future predictions less wrong.',
        guidedExample: 'If a model predicts 290,000 dollars for a house worth 300,000 dollars, the error contributes to loss. Training changes weights so similar predictions move closer to reality.',
        bridge: 'AI combines functions, probability, derivatives, data structures, algorithms, and physical hardware that performs the computation.',
        prediction: {
          question: 'If training lowers loss on useful examples, what do you predict happens to model predictions?',
          answer: 'They usually improve, because the model has adjusted toward smaller errors.',
        },
        quiz: {
          question: 'What is loss in machine learning?',
          options: ['A measure of prediction error', 'A guarantee that the answer is true', 'The voltage in a circuit', 'A type of loop'],
          correctIndex: 0,
          feedback: [
            'Correct. Loss measures how wrong predictions are.',
            'No. AI predictions are not guaranteed true.',
            'No. Voltage is an electrical quantity.',
            'No. Loops can be used in training, but loss is not a loop.',
          ],
        },
      },
    ],
  },
};
