export const thinkingChallenges = [
  {
    id: 'thinking-two-truths-logic',
    type: 'Logic puzzle',
    difficulty: 'Beginner',
    title: 'Two Truths and a Lie',
    problem: 'A box has three labels: "red", "blue", and "mixed". All labels are wrong. You may look at one item from one box. Which box should you sample first, and why?',
    solution: 'Sample the box labeled "mixed". Because every label is wrong, that box is not mixed. If the item is red, the whole box is red; if it is blue, the whole box is blue. Then the remaining labels can be assigned by elimination.',
    reasoning: 'The trick is to use the strongest constraint: every label is wrong. Sampling the box labeled mixed gives a definite answer because that box must contain only one color.',
  },
  {
    id: 'thinking-pattern-differences',
    type: 'Pattern recognition',
    difficulty: 'Beginner',
    title: 'Difference Pattern',
    problem: 'Find the next number: 2, 5, 9, 14, 20, __. Explain the pattern.',
    solution: '27',
    reasoning: 'The differences are +3, +4, +5, +6. The next difference should be +7, so 20 + 7 = 27.',
  },
  {
    id: 'thinking-what-if-friction',
    type: 'What happens if',
    difficulty: 'Core',
    title: 'Remove Friction',
    problem: 'What happens if a hockey puck slides on a perfectly frictionless surface after being pushed once?',
    solution: 'It keeps moving at constant velocity in a straight line unless another force acts.',
    reasoning: 'Without friction, there is no horizontal force to slow it down. Newtons first law says motion stays unchanged when net force is zero.',
  },
  {
    id: 'thinking-open-ended-study-tool',
    type: 'Open-ended problem',
    difficulty: 'Core',
    title: 'Design a Better Study Tool',
    problem: 'Design one feature that would help a learner notice weak understanding before a test. What input would it need, and what output should it give?',
    solution: 'One strong answer: use missed quiz answers, unfinished reflections, and weak self-grades as inputs. Output a review queue with reasons and quick links.',
    reasoning: 'Open-ended problems are judged by structure. A good answer names inputs, processing logic, outputs, and how the learner would use the result.',
  },
  {
    id: 'thinking-counterexample-game',
    type: 'Mini game',
    difficulty: 'Advanced',
    title: 'Counterexample Hunt',
    problem: 'Claim: "If two things happen together, one caused the other." Find a counterexample.',
    solution: 'Ice cream sales and sunburns rise together, but hot weather can cause both. The correlation does not prove ice cream causes sunburn.',
    reasoning: 'A counterexample breaks an overbroad claim. It is one of the fastest ways to test whether a rule is too strong.',
  },
  {
    id: 'thinking-algorithm-choice',
    type: 'Logic puzzle',
    difficulty: 'Core',
    title: 'Choose the Search',
    problem: 'You have a sorted list of 1,000 names. You need one name quickly. Should you check from the start or repeatedly cut the search space in half?',
    solution: 'Repeatedly cut the search space in half.',
    reasoning: 'Because the list is sorted, binary search can eliminate half the remaining names each step. That is much faster than checking up to 1,000 names one by one.',
  },
  {
    id: 'thinking-ambiguous-instruction',
    type: 'Critical thinking',
    difficulty: 'Beginner',
    title: 'Fix the Ambiguity',
    problem: 'Rewrite this instruction so it cannot be misunderstood: "Put the data in the file after cleaning it."',
    solution: 'Clean the data first. Then save the cleaned data in the file.',
    reasoning: 'The original sentence leaves "it" unclear. Clear instructions name the object and order the steps.',
  },
  {
    id: 'thinking-systems-feedback',
    type: 'What happens if',
    difficulty: 'Advanced',
    title: 'Feedback Delay',
    problem: 'What happens if a thermostat reacts very slowly after the room temperature changes?',
    solution: 'The room may overshoot the target: it can get too hot or too cold before the thermostat corrects.',
    reasoning: 'Feedback systems depend on timing. Delayed feedback can cause oscillation because corrections arrive after the system has already moved past the goal.',
  },
];
